crates/testing/src/slt/cli.rs

Closes https://github.com/GlareDB/glaredb/issues/1006

chore: Manually abort on panic for slt tests

---

Cargo.lock
crates/datafusion_planner/Cargo.toml
crates/datasources/Cargo.toml
crates/glaredb/Cargo.toml
crates/metastore/Cargo.toml
crates/object_store_util/Cargo.toml
crates/pgrepr/Cargo.toml
crates/pgsrv/Cargo.toml
crates/repr/Cargo.toml
crates/snowflake_connector/Cargo.toml
crates/sqlexec/Cargo.toml

- Closes #1078
- Closes #1077
- Closes #1076
- Closes #1075
- Closes #1074
- Closes #1073

build(deps): Bump deps

---

crates/sqlexec/src/context.rs

fix: max datasource and tunnel counting

---

crates/datafusion_planner/src/relation/mod.rs
crates/sqlbuiltins/src/errors.rs
crates/sqlbuiltins/src/functions.rs
testdata/sqllogictests/functions/generate_series.slt

Adds the function
```
p=> select * from generate_series(1, 4);
generate_series
-----------------
1
2
3
4
(4 rows)
p=> select * from generate_series(4, 1, -1);
generate_series
-----------------
4
3
2
1
(4 rows)
p=> select * from generate_series(1, 4, -1);
generate_series
-----------------
(0 rows)
```

feat: Add `generate_series` function

---

crates/metastore/src/srv.rs

This reverts commit e0d0c66d7f442072a7e385944499e836e4ece011.

Revert "chore: Log error if failed to find catalog (#1173)"

---

crates/sqlbuiltins/src/functions.rs

fix: allow file & relative urls for *_scan

---

Cargo.lock
crates/testing/Cargo.toml
crates/testing/src/slt/cli.rs
crates/testing/src/slt/test.rs
crates/testing/tests/sqllogictests/main.rs

Hopefully fixes our timeout woes.
Closes https://github.com/GlareDB/glaredb/issues/1204

chore: Break up slt tests into batches

---

py-glaredb/src/lib.rs

check permissions on tmp dir

---

scripts/protocol-test.sh

chore: Remove starting metastore from pgproto test script

---

.github/workflows/image.yaml
.github/workflows/python-release.yaml
.github/workflows/release.yaml
Cargo.lock
py-glaredb/Cargo.toml

ci: Keep py-glaredb and glaredb versions in sync 

---

crates/pgsrv/src/proxy.rs

chore: Add test cases for parsing compute engine from conn string

---

crates/datasources/src/object_store/local.rs

Changed the logic to fetch filetype only if it is not provided
fixes #1284

fix: don't fetch filetype eagerly

---

crates/datasources/src/object_store/registry.rs
crates/sqlexec/src/context.rs

Should fix panics.
Closes https://github.com/GlareDB/glaredb/issues/1289

feat: Add s3 to object store registry create

---

crates/sqlexec/src/session.rs
justfile
py-glaredb/src/lib.rs
py-glaredb/src/logical_plan.rs
py-glaredb/src/session.rs

feat(py): add lazy execution to python

---

Cargo.lock
crates/sqlbuiltins/Cargo.toml
crates/sqlbuiltins/src/errors.rs
crates/sqlbuiltins/src/functions.rs
testdata/sqllogictests/functions/generate_series.slt

feat: Add support for float in generate_series

---

crates/datasources/src/object_store/http.rs
testdata/sqllogictests/functions/parquet_scan.slt

Closes https://github.com/GlareDB/glaredb/issues/1318

fix: Fix not being able to read huggingface parquets

---

testdata/sqllogictests/table.slt

Fixed by update to deltalake.
Closes https://github.com/GlareDB/glaredb/issues/1321

chore: Add test for inserting lists into table

---

.github/dependabot.yml

Too many notifications. I already know they're happening on Friday.

chore: Remove myself from dependabot reviews

---

Cargo.lock
crates/bench_runner/Cargo.toml
crates/datasources/Cargo.toml
crates/glaredb/Cargo.toml
crates/metastore/Cargo.toml
crates/metastore_client/Cargo.toml
crates/object_store_util/Cargo.toml
crates/pgprototest/Cargo.toml
crates/pgsrv/Cargo.toml
crates/slt_runner/Cargo.toml
crates/snowflake_connector/Cargo.toml
crates/sqlbuiltins/Cargo.toml
crates/sqlexec/Cargo.toml
crates/telemetry/Cargo.toml
crates/testing/Cargo.toml
py-glaredb/Cargo.toml
xtask/Cargo.toml

- Closes #1390
- Closes #1389
- Closes #1387

build(deps): Bump even more deps

---

py-glaredb/examples/multiple.py
py-glaredb/examples/openai_ex.py
py-glaredb/examples/pandas_interop.py
py-glaredb/examples/polars_interop.py
py-glaredb/examples/show.py
py-glaredb/src/lib.rs
py-glaredb/src/session.rs
py-glaredb/tests/test_logical_plan.py
py-glaredb/tests/test_pandas.py
py-glaredb/tests/test_polars.py

feat: add close method to python

---

.github/workflows/ci.yaml

ci: update scripts to only run integration tests when owner = glaredb

---

testdata/sqllogictests/time.slt

chore: Add some time related slts

---

testdata/README.md
testdata/sqllogictests_iceberg/gcs.slt
testdata/sqllogictests_iceberg/s3.slt

Addresses S3/GCS task in https://github.com/GlareDB/glaredb/issues/1448

chore: Add SLTs for Iceberg + S3/GCS

---

testdata/sqllogictests_object_store/gcs/external_table.slt
testdata/sqllogictests_object_store/local/external_table.slt
testdata/sqllogictests_object_store/s3/external_table.slt

Featuring globs, credentials and `file_type` parameter.
Fixes #1449

test: Add SLTs for object store external tables

---

crates/glaredb/src/highlighter.rs

fix(cli): highlight insert into ... values

---

Dockerfile

Maybe this will fix failing to get deltalake?

chore: Update rust version in docker file

---

testdata/sqllogictests/functions/csv_scan.slt
testdata/sqllogictests/functions/delta_scan.slt
testdata/sqllogictests/functions/json_scan.slt
testdata/sqllogictests/functions/parquet_scan.slt

test: Fix relative path scan tests

---

Cargo.lock
crates/glaredb/Cargo.toml
crates/glaredb/src/server.rs

Needed to run rpcsrv in the background

fix: Fix pg handler not running

---

crates/glaredb/src/local.rs

feat: Allow "exit" and "\q" to exit cli

---

crates/protogen/proto/rpcsrv/service.proto
crates/rpcsrv/src/handler.rs
crates/rpcsrv/src/proxy.rs
crates/sqlexec/src/context.rs

feat: close remote sessions on exit

---

crates/datasources/src/native/access.rs

fix: number of deleted rows returned when there is no where clause

---

crates/arrow_util/src/pretty.rs

fix: bug with printing tables that has multiple record batches

---

crates/glaredb/src/highlighter.rs
crates/glaredb/src/local.rs

fix client command validation for cli

---

crates/protogen/src/sqlexec/logical_plan.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/planner/extension.rs
crates/sqlexec/src/planner/logical_plan/alter_database_rename.rs
crates/sqlexec/src/planner/logical_plan/alter_table_rename.rs
crates/sqlexec/src/planner/logical_plan/alter_tunnel_rotate_keys.rs
crates/sqlexec/src/planner/logical_plan/create_table.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/session.rs

this implements remote exec for the following;

feat(rpcsrv): rpc alter stmts

---

crates/rpcsrv/src/session.rs
crates/sqlexec/src/context.rs
crates/sqlexec/src/planner/dispatch.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/session.rs

fix: Use actual session context in remote session

---

crates/glaredb/src/highlighter.rs
crates/protogen/src/metastore/types/options.rs
crates/protogen/src/sqlexec/logical_plan.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/planner/extension.rs
crates/sqlexec/src/planner/logical_plan.rs
crates/sqlexec/src/planner/logical_plan/alter_database_rename.rs
crates/sqlexec/src/planner/logical_plan/alter_table_rename.rs
crates/sqlexec/src/planner/logical_plan/alter_tunnel_rotate_keys.rs
crates/sqlexec/src/planner/logical_plan/create_credentials.rs
crates/sqlexec/src/planner/logical_plan/create_external_database.rs
crates/sqlexec/src/planner/logical_plan/create_external_table.rs
crates/sqlexec/src/planner/logical_plan/create_schema.rs
crates/sqlexec/src/planner/logical_plan/create_table.rs
crates/sqlexec/src/planner/logical_plan/create_tunnel.rs
crates/sqlexec/src/planner/logical_plan/drop_tables.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/session.rs

adds rpc for the rest of the create statements. 
also a small refactor to the extensions so that we have exhaustive pattern matching. (was finding myself missing a few spots when adding a new extension node). Should be a bit easier as it'll compile error now.

feat: rpc for create stmts

---

crates/datasources/src/bigquery/mod.rs

feat: support record, struct, big numeric type for bigquery

---

crates/protogen/src/sqlexec/logical_plan.rs
crates/sqlexec/src/context.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/planner/extension.rs
crates/sqlexec/src/planner/logical_plan/create_temp_table.rs
crates/sqlexec/src/planner/logical_plan/create_tunnel.rs
crates/sqlexec/src/planner/logical_plan/create_view.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/session.rs

finish up the rest of the create statements for remote exec.

feat: temp table & view for remote exec

---

crates/glaredb/src/highlighter.rs
crates/protogen/src/sqlexec/logical_plan.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/planner/extension.rs
crates/sqlexec/src/planner/logical_plan.rs
crates/sqlexec/src/planner/logical_plan/drop_credentials.rs
crates/sqlexec/src/planner/logical_plan/drop_database.rs
crates/sqlexec/src/planner/logical_plan/drop_schemas.rs
crates/sqlexec/src/planner/logical_plan/drop_tunnel.rs
crates/sqlexec/src/planner/logical_plan/drop_views.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/session.rs

also adds in a few more keywords for cli highlighting.

feat: rpc for drop ddls

---

crates/protogen/src/metastore/types/options.rs
crates/protogen/src/sqlexec/logical_plan.rs
crates/protogen/src/sqlexec/logical_plan/copy_to.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/planner/extension.rs
crates/sqlexec/src/planner/logical_plan.rs
crates/sqlexec/src/planner/logical_plan/alter_database_rename.rs
crates/sqlexec/src/planner/logical_plan/alter_table_rename.rs
crates/sqlexec/src/planner/logical_plan/alter_tunnel_rotate_keys.rs
crates/sqlexec/src/planner/logical_plan/copy_to.rs
crates/sqlexec/src/planner/logical_plan/create_credentials.rs
crates/sqlexec/src/planner/logical_plan/create_external_database.rs
crates/sqlexec/src/planner/logical_plan/create_external_table.rs
crates/sqlexec/src/planner/logical_plan/create_schema.rs
crates/sqlexec/src/planner/logical_plan/create_table.rs
crates/sqlexec/src/planner/logical_plan/create_temp_table.rs
crates/sqlexec/src/planner/logical_plan/create_tunnel.rs
crates/sqlexec/src/planner/logical_plan/create_view.rs
crates/sqlexec/src/planner/logical_plan/drop_credentials.rs
crates/sqlexec/src/planner/logical_plan/drop_database.rs
crates/sqlexec/src/planner/logical_plan/drop_schemas.rs
crates/sqlexec/src/planner/logical_plan/drop_tables.rs
crates/sqlexec/src/planner/logical_plan/drop_tunnel.rs
crates/sqlexec/src/planner/logical_plan/drop_views.rs
crates/sqlexec/src/planner/logical_plan/set_variable.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/session.rs

Want to get this in ASAP to prevent any conflicts with other extension work. 
we couldn't continue using `TryFrom` as we need to deserialize the nested plans, and that requires a codec & context. 
closes https://github.com/GlareDB/glaredb/issues/1565

small refactor to ExtensionNode

---

crates/datasources/src/postgres/errors.rs
crates/datasources/src/postgres/mod.rs
crates/protogen/src/sqlexec/common.rs
crates/protogen/src/sqlexec/mod.rs
crates/protogen/src/sqlexec/physical_plan.rs
crates/protogen/src/sqlexec/table_provider.rs
crates/sqlbuiltins/src/functions/postgres.rs
crates/sqlexec/src/planner/dispatch.rs

chore: Add prost messages for postgres physical plan and table provider

---

crates/glaredb/src/util.rs
crates/sqlexec/src/background_jobs/storage.rs
crates/sqlexec/src/engine.rs
crates/sqlexec/src/errors.rs
crates/sqlexec/src/metastore/catalog.rs
crates/sqlexec/src/metastore/client.rs

Also:
- Renames some types to be clearer
- Add keepalive to metastore client channel (hopefully this cuts down on stale connections)

chore: Add some docs to metastore client module

---

crates/sqlexec/src/remote/client.rs

fix: Append auth metadata to streaming request

---

Cargo.lock
py-glaredb/Cargo.toml
py-glaredb/src/error.rs
py-glaredb/src/lib.rs
py-glaredb/src/session.rs

feat: Allow connecting to cloud deployment with python bindings

---

crates/protogen/src/sqlexec/logical_plan.rs
crates/protogen/src/sqlexec/physical_plan.rs
crates/sqlexec/src/background_jobs/storage.rs
crates/sqlexec/src/context/local.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/planner/extension.rs
crates/sqlexec/src/planner/logical_plan.rs
crates/sqlexec/src/planner/logical_plan/insert.rs
crates/sqlexec/src/planner/physical_plan/create_table.rs
crates/sqlexec/src/planner/physical_plan/insert.rs
crates/sqlexec/src/planner/physical_plan/mod.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/remote/planner.rs
crates/sqlexec/src/session.rs

feat: Insert

---

crates/protogen/src/sqlexec/logical_plan.rs
crates/protogen/src/sqlexec/physical_plan.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/planner/extension.rs
crates/sqlexec/src/planner/logical_plan.rs
crates/sqlexec/src/planner/logical_plan/show_variable.rs
crates/sqlexec/src/planner/physical_plan/create_table.rs
crates/sqlexec/src/planner/physical_plan/mod.rs
crates/sqlexec/src/planner/physical_plan/set_var.rs
crates/sqlexec/src/planner/physical_plan/show_var.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/remote/planner.rs
crates/sqlexec/src/session.rs

feat: SET/SHOW Variables

---

crates/protogen/src/sqlexec/physical_plan.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/planner/logical_plan.rs
crates/sqlexec/src/planner/physical_plan/copy_to.rs
crates/sqlexec/src/planner/physical_plan/mod.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/remote/planner.rs
crates/sqlexec/src/session.rs

chore: Copy To

---

crates/datafusion_ext/src/vars.rs
crates/datasources/src/lake/iceberg/spec/metadata.rs
crates/datasources/src/lake/iceberg/spec/schema.rs
crates/decimal/src/lib.rs
crates/pgsrv/src/handler.rs
crates/snowflake_connector/src/query.rs

With new rust update, come new clippy responsibilities.
Fixes #1638

chore: chore: Resolve clippy errors

---

crates/sqlexec/src/planner/context_builder.rs

```
> create external table my_parquet
::: from local (
::: location 'testdata/parquet/userdata1.parquet'
::: );
Table created
> select count(*) from my_parquet;
┌─────────────────┐
│ COUNT(UInt8(1)) │
│ ──              │
│ Int64           │
╞═════════════════╡
│ 1000            │
└─────────────────┘
```

fix: Dispatch local external table locally with RPC

---

Cargo.lock
crates/object_store_util/Cargo.toml
crates/object_store_util/src/conf.rs

fix: Make in-memory store persistent

---

crates/datasources/src/native/access.rs
testdata/sqllogictests/rpc.slt

fix: remote_scan panic on empty native table

---

.github/workflows/ci.yaml
testdata/sqllogictests/credentials.slt

We have a good chunk running right now. I opened up some issues for stuff that I came across that doesn't work.

chore: Enable more SLT tests for RPC

---

testdata/sqllogictests/functions/parquet_scan.slt

Closes https://github.com/GlareDB/glaredb/issues/1682

chore: Update hugging face parquet file

---

crates/sqlexec/src/planner/physical_plan/client_send.rs

fix: broadcasting empty stream

---

crates/glaredb/src/highlighter.rs
crates/glaredb/src/local.rs

not much, but a nice UX improvement. It's a modified version of the DefaultHinter to work with our styling, otherwise the implementation is identical to the DefaultHinter.

feat: add history hinting to cli

---

Cargo.lock
Cargo.toml

PR merged.
I also force pushed `fork` so build will start breaking anyways...

chore: Point back to upstream delta-rs

---

crates/datafusion_ext/src/functions.rs
crates/metastore/src/database.rs
crates/protogen/proto/metastore/catalog.proto
crates/protogen/src/metastore/types/catalog.rs
crates/sqlbuiltins/src/functions/generate_series.rs
crates/sqlbuiltins/src/functions/object_store.rs
crates/sqlexec/src/planner/context_builder.rs
crates/sqlexec/src/planner/session_planner.rs

fix: rpc create table subqueries

---

crates/sqlbuiltins/src/functions/virtual_listing.rs
crates/sqlexec/src/dispatch/external.rs

fix: list schemas & tables

---

crates/datasources/src/object_store/mod.rs
crates/sqlbuiltins/src/functions/object_store.rs
testdata/sqllogictests/functions/parquet_scan.slt

Throw an error if any file location returns an empty list
Fixes #1695

fix: Throw error on invalid file paths

---

crates/pgsrv/src/handler.rs

`node-postgres` always sends an auth message when trying to connect even when the backend replies with `AuthenticationOk`. This hangs the handler when trying to connect using `psql` since the handler keeps on waiting for a new message which it would never receive.
We simply ask the frontend to send a password when `--ignore-pg-auth` flag is passed (since that's what `node-postgres` does), ignore the password message and move on like nothing happened. However, this does require that there's only 1 password message.
Fixes #1663

fix: Ask for password each time we want to ignore it (pgsrv).

---

crates/glaredb/src/args/local.rs
crates/glaredb/src/local.rs
crates/glaredb/src/util.rs

chore: remove "metastore-addr" from local

---

py-glaredb/tests/test_logical_plan.py

fix: pydict order issue in python test

---

crates/glaredb/src/args/local.rs

chore: update cloud-url --help text

---

crates/datasources/src/mongodb/infer.rs

Left a comment in code, but we'll want to determine if this is something we should keep around. Currently mongodb will read empty values in a csv as an empty string and not null, and so we were widening types from Float64 to Utf8 when encountering an empty string in tests, leading to a flake.
This change just assumes we can't infer anything from an empty string, which will let us widen to the correct type when merging schemas.
Fixes #1733

fix: Be resilient to empty string values in mongo

---

Cargo.lock
crates/arrow_util/Cargo.toml
crates/arrow_util/src/pretty.rs
crates/glaredb/src/args/local.rs
crates/glaredb/src/local.rs
py-glaredb/src/session.rs

Terminal width, no hidden columns:
Terminal width, no hidden columns, no record batches:
80 char width, hidden columns:
Explian (multi line string):

feat: Better pretty table handling

---

README.md

These updates shouldn't merge until after release.
Resolves: #1716

chore: readme updates for 0.5.0

---

.github/workflows/ci.yaml
.github/workflows/python-release.yaml
.github/workflows/release.yaml

Closes: https://github.com/GlareDB/glaredb/issues/1648

ci: pin rust version in CI

---

.github/workflows/ci.yaml
scripts/protocol-test.sh

My CI build ran for 11 minutes. That seems long, let's see what this is like.

ci: fanout CI steps for parallel build

---

crates/arrow_util/src/pretty.rs

Fixes https://github.com/GlareDB/glaredb/issues/1790

fix: Fix underflow when formatting large number of columns

---

.github/workflows/ci.yaml

Was working through some stuff with Grey, and realize that the labels
and divisions between steps here were confusing.

ci: improve labeling of slt tests

---

crates/arrow_util/src/pretty.rs

fix: single column with long header

---

crates/metastore/src/database.rs
crates/metastore/src/errors.rs
crates/protogen/proto/metastore/service.proto
crates/protogen/src/metastore/types/service.rs
crates/protogen/src/sqlexec/logical_plan.rs
crates/protogen/src/sqlexec/physical_plan.rs
crates/sqlexec/src/extension_codec.rs
crates/sqlexec/src/parser.rs
crates/sqlexec/src/planner/logical_plan/create_external_table.rs
crates/sqlexec/src/planner/physical_plan/create_external_table.rs
crates/sqlexec/src/planner/session_planner.rs
crates/sqlexec/src/remote/planner.rs
testdata/sqllogictests/external_table.slt

fix: create or replace for external tables

---

py-glaredb/src/environment.rs
py-glaredb/tests/test_polars.py

Quick fix for querying polars lazy frames by collecting the result in memory.
A more robust solution for lazy frames may be forthcoming.

feat: Support polars lazy frames (the lazy way)

---

crates/datasources/src/common/util.rs
crates/datasources/src/mysql/mod.rs
crates/datasources/src/postgres/mod.rs
crates/datasources/src/postgres/query_exec.rs

feat: support insert into for mysql

---

Cargo.lock
crates/arrow_util/src/pretty.rs
crates/datafusion_ext/src/functions.rs
crates/metastore/src/database.rs
crates/protogen/proto/metastore/catalog.proto
crates/protogen/src/metastore/types/catalog.rs
crates/sqlbuiltins/Cargo.toml
crates/sqlbuiltins/src/builtins.rs
crates/sqlbuiltins/src/functions/bigquery.rs
crates/sqlbuiltins/src/functions/generate_series.rs
crates/sqlbuiltins/src/functions/mod.rs
crates/sqlbuiltins/src/functions/mongo.rs
crates/sqlbuiltins/src/functions/mysql.rs
crates/sqlbuiltins/src/functions/object_store.rs
crates/sqlbuiltins/src/functions/postgres.rs
crates/sqlbuiltins/src/functions/snowflake.rs
crates/sqlbuiltins/src/functions/virtual_listing.rs
crates/sqlexec/Cargo.toml
crates/sqlexec/src/dispatch/system.rs
crates/sqlexec/src/metastore/catalog.rs

closes https://github.com/GlareDB/glaredb/issues/1798

feat: extend builtin function catalog

---

crates/datasources/src/native/access.rs
crates/sqlexec/src/background_jobs/storage.rs
crates/sqlexec/src/planner/physical_plan/create_table.rs
testdata/sqllogictests/external_table.slt
testdata/sqllogictests/table.slt
testdata/sqllogictests/temp_table.slt

fix: Resolve `IF NOT EXISTS` for native tables

---

crates/object_store_util/src/conf.rs
crates/sqlexec/src/engine.rs

fix: Return memory store if engine not configured to work with session bucket

---

crates/sqlexec/src/context/local.rs
crates/sqlexec/src/metrics.rs
crates/sqlexec/src/session.rs

chore: Update `bytes_processed` param to `bytes_read`.

---

.github/workflows/benchmarks.yaml
.github/workflows/ci.yaml
.github/workflows/python-release.yaml
.github/workflows/release.yaml
Dockerfile
benchmarks/justfile
benchmarks/tpch/justfile
crates/decimal/src/lib.rs
justfile
py-glaredb/justfile

See also https://github.com/GlareDB/glaredb/issues/1940 for chance to remove some yaml.

chore: Proper rust toolchain setup for all steps, bump rust version

---

crates/metastore/src/database.rs
crates/sqlbuiltins/src/functions/mod.rs

feat: add aggregate functions to builtin catalog

---

justfile

chore: Enable more rpc tests

---

crates/glaredb/src/args/mod.rs
crates/glaredb/src/commands.rs
crates/glaredb/src/rpc_proxy.rs
crates/sqlexec/src/remote/client.rs

feat(tls): make tls mode configurable

---

crates/glaredb/src/local.rs

fix(minor): cleanup interactive startup message

---

crates/glaredb/src/local.rs
crates/sqlexec/src/remote/client.rs
js-glaredb/src/connection.rs
py-glaredb/src/connect.rs

Written with only the best DX via WSL and a personal Rust coach

feat(tls): cloud auth fields for api_version, client_type

---

crates/sqlexec/src/session.rs
js-glaredb/src/connection.rs
py-glaredb/src/connection.rs

Closes #2011
(just wanted to see if this is the right approach before I dug further
into this (and also let CI tell me if I broke something major))

feat(prql): add direct pqrl bindings to helpers

---

Cargo.lock
crates/datafusion_ext/Cargo.toml
crates/datafusion_ext/src/planner/relation/mod.rs
crates/datasources/Cargo.toml
crates/datasources/src/object_store/local.rs
crates/ioutil/Cargo.toml
crates/ioutil/src/lib.rs
crates/sqlbuiltins/Cargo.toml
crates/sqlbuiltins/src/functions/excel.rs

closes https://github.com/GlareDB/glaredb/issues/2033

fix: allow tilde paths

---

Cargo.lock
bindings/nodejs/Cargo.toml
bindings/nodejs/src/record_batch.rs
crates/datasources/Cargo.toml
crates/pgsrv/Cargo.toml
crates/testing/Cargo.toml
testdata/sqllogictests/functions/generate_series.slt

- Closes #2078
- Closes #2079
- Closes #2077
- Closes #2075
- Closes #2076
- Closes #2074
- Closes #2072
- Closes #2073
- Closes #2071

chore(deps): Bump deps

---

.github/workflows/ci.yaml
.github/workflows/nodejs-release.yml

chore(deps): Bump actions deps

---

crates/sqlexec/src/parser.rs
testdata/sqllogictests/parser.slt

Closes https://github.com/GlareDB/glaredb/issues/2116

feat: Allow trailing commas in select list

---

crates/datasources/src/mongodb/infer.rs

Was poking around this to write docs, and saw some room for improvement.

fix(mongodb): improvements to schema inference

---

crates/sqlexec/src/functions.rs
testdata/sqllogictests/functions/kdl.slt

builds upon and extends #2145 with a corresponding projection. 
it also ends up including some refactors to the matcher for common use. 
If you have not read and approved #2145 do that before approving this.

feat(kdl): kdl_select function

---

.github/workflows/ci.yaml
.github/workflows/image.yaml
.github/workflows/nodejs-release.yml
.github/workflows/pr-cleanup.yaml
.github/workflows/python-release.yaml
.github/workflows/release.yaml

Closes: #2259
Closes: #2260
Closes: #2261

chore(deps): upgrade actions

---

crates/sqlbuiltins/src/functions/table/mod.rs
crates/sqlbuiltins/src/functions/table/sqlserver.rs
testdata/sqllogictests_sqlserver/read.slt

```sql
SELECT * FROM read_sqlserver(
-- Connection string
'server=tcp:localhost,1433;user=SA;password=bigStrong@1Pwd;TrustServerCertificate=true',
-- Schema name
'dbo',
-- Table name
'my_table'
);
```

feat: Add `read_sqlserver` table returning function

---

.gitignore
Cargo.lock
crates/datasources/Cargo.toml
crates/datasources/src/clickhouse/errors.rs
crates/datasources/src/clickhouse/mod.rs
crates/datasources/src/clickhouse/stream.rs
crates/datasources/src/common/util.rs
crates/protogen/proto/metastore/options.proto
crates/protogen/src/metastore/types/options.rs
crates/sqlbuiltins/src/functions/table/clickhouse.rs
crates/sqlbuiltins/src/functions/table/virtual_listing.rs
crates/sqlexec/src/dispatch/external.rs
crates/sqlexec/src/planner/session_planner.rs
scripts/create-test-clickhouse-db.sh
testdata/sqllogictests_clickhouse/data/setup-clickhouse.sql
testdata/sqllogictests_clickhouse/datatypes.slt
testdata/sqllogictests_clickhouse/external_database.slt
testdata/sqllogictests_clickhouse/external_table.slt
testdata/sqllogictests_clickhouse/read.slt

See tests for changes to read function (schema optional).
To connect to cloud:
```
> CREATE EXTERNAL DATABASE click_cloud
::: FROM clickhouse (
::: connection_string 'clickhouse://default:<PWD>@gfvi4aovgg.us-east1.gcp.clickhouse.cloud/?secure'
::: );
Database created
```
Fixes: #2315

feat: Clickhouse followup items

---

Cargo.lock
Cargo.toml
bindings/nodejs/package.json

Revert "release: v0.8.0"

---

Cargo.lock
Cargo.toml
bindings/nodejs/package.json

release: v0.8.0

---

crates/glaredb/src/highlighter.rs

Fixes #2114 
A dedicated highlighting logic for PRQL queries is desired in future.

Fix : Adding keywords for PRQL for higlighting

---

.github/workflows/nodejs-release.yml
.github/workflows/python-release.yaml
.github/workflows/release.yaml

Closes https://github.com/GlareDB/glaredb/issues/2431

chore: Post release build results to slack

---

.github/workflows/benchmarks.yaml
.github/workflows/ci.yaml
.github/workflows/nodejs-release.yml
.github/workflows/python-release.yaml
.github/workflows/release.yaml

chore(ci): pin just version

---

Cargo.lock
Cargo.toml
bindings/python/Cargo.toml
crates/catalog/Cargo.toml
crates/datafusion_ext/Cargo.toml
crates/datasources/Cargo.toml
crates/glaredb/Cargo.toml
crates/metastore/Cargo.toml
crates/object_store_util/Cargo.toml
crates/pgsrv/Cargo.toml
crates/protogen/Cargo.toml
crates/proxyutil/Cargo.toml
crates/rpcsrv/Cargo.toml
crates/slt/Cargo.toml
crates/snowflake_connector/Cargo.toml
crates/sqlbuiltins/Cargo.toml
crates/sqlexec/Cargo.toml
crates/telemetry/Cargo.toml
testdata/sqllogictests/prql.slt

- Closes #2456
- Closes #2458
- Closes #2455
- Closes #2454
- Closes #2452
- Closes #2450
- Closes #2451

chore(deps): Bump rust deps

---

testdata/sqllogictests/prql.slt

chore: Run more prql integration tests

---

.github/workflows/release.yaml

chore(binary build): slack alert

---

crates/sqlexec/src/context/local.rs
crates/sqlexec/src/lib.rs
crates/sqlexec/src/optimizer.rs

todo: add some unit tests for this.

fix: optimize ddl subqueries

---

crates/glaredb/src/local.rs

100 is too short. I want 'all' of my history.

chore: increase the history length for cli

---

crates/sqlexec/src/planner/session_planner.rs
testdata/sqllogictests/create_view.slt

closes https://github.com/GlareDB/glaredb/issues/2636

fix: create view nested query

---

crates/datafusion_ext/src/planner/relation/mod.rs
testdata/sqllogictests/xlsx.slt

fix: infer excel files by extension

---

crates/datasources/src/excel/mod.rs
crates/sqlbuiltins/src/functions/table/excel.rs
testdata/sqllogictests/xlsx.slt

fix: excel files should default to having a header like csv files

---

bindings/nodejs/package.json

Based on <https://napi.rs/docs/cli/pre-publish#flags>
Resolves: #2399

chore(release): napi --skip-gh-release

---

crates/sqlbuiltins/src/functions/mod.rs
crates/sqlbuiltins/src/functions/scalars/kdl.rs
justfile

This is a part of #2015.
I mirrored the implementation from the similarity function.

fix: kdl support in hybrid

---

benchmarks/tpch/duckdb_queries/__init__.py
benchmarks/tpch/glaredb_queries/__init__.py
benchmarks/tpch/polars_queries/__init__.py
bindings/python/tests/__init__.py
tests/fixtures/__init__.py

chore: add note to python __init__.py files

---

crates/sqlbuiltins/Cargo.toml

specifying branch is more clear than hash

chore: change lance ref

---

Cargo.lock
Cargo.toml
crates/datasources/Cargo.toml
crates/sqlbuiltins/Cargo.toml

Closes #2791
Closes #2790
Closes #2789
Closes #2788
Closes #2787
Closes #2786
Closes #2785

chore: deps upgrade 2024-03-15

---

benchmarks/tpch/requirements.txt
bindings/python/requirements.txt

chore(deps): bump black from 23.3.0 to 24.3.0

---

Cargo.lock
Cargo.toml
bindings/python/Cargo.toml
crates/catalog/Cargo.toml
crates/datafusion_ext/Cargo.toml
crates/datasources/Cargo.toml
crates/glaredb/Cargo.toml
crates/metastore/Cargo.toml
crates/object_store_util/Cargo.toml
crates/pgsrv/Cargo.toml
crates/protogen/Cargo.toml
crates/proxyutil/Cargo.toml
crates/rpcsrv/Cargo.toml
crates/slt/Cargo.toml
crates/snowflake_connector/Cargo.toml
crates/sqlbuiltins/Cargo.toml
crates/sqlexec/Cargo.toml
crates/telemetry/Cargo.toml

Closes #2821
Closes #2820
Closes #2819
Closes #2818
Closes #2817
Closes #2816
Closes #2815

chore: dependency updates 2024-03-25

---

flake.nix

fix: nix agpl spec

---

Cargo.lock
Cargo.toml
crates/catalog/Cargo.toml
crates/datafusion_ext/Cargo.toml
crates/datasources/Cargo.toml
crates/distexec/Cargo.toml
crates/slt/Cargo.toml
crates/snowflake_connector/Cargo.toml
crates/sqlbuiltins/Cargo.toml
crates/sqlexec/Cargo.toml
xtask/Cargo.toml
xtask/src/main.rs

Closes #2946
Closes #2945
Closes #2944
Closes #2943
Closes #2942
Closes #2941
Closes #2940
Closes #2939
Closes #2938
Closes #2937

chore(deps): upgrade dependencies

---

crates/rayexec_execution/src/functions/aggregate/mod.rs
crates/rayexec_execution/src/functions/aggregate/stddev.rs
slt/standard/aggregates/functions/stddev.slt

Adds `stddev_pop`, `stddev_samp`, `var_pop`, and `var_samp` functions.

feat: stddev aggregates

---

Cargo.lock
crates/rayexec_execution/Cargo.toml
crates/rayexec_execution/src/logical/binder/expr_binder.rs
crates/rayexec_execution/src/logical/resolver/expr_resolver.rs
crates/rayexec_wasm/Cargo.toml

Previous version we were using.

chore: Pin wasm-bindgen to 0.2.92

---

Cargo.lock
Cargo.toml

- Closes #3373 
- Closes #3374

chore: Bump deps

---

crates/rayexec_execution/src/arrays/array/array_buffer.rs
crates/rayexec_execution/src/arrays/array/mod.rs
crates/rayexec_execution/src/arrays/array/physical_type.rs
crates/rayexec_execution/src/arrays/array/raw.rs
crates/rayexec_execution/src/arrays/array/string_view.rs
crates/rayexec_execution/src/arrays/executor/builder.rs
crates/rayexec_execution/src/arrays/executor/scalar/fill.rs
crates/rayexec_execution/src/arrays/executor/scalar/hash.rs
crates/rayexec_execution/src/arrays/executor/scalar/list.rs
crates/rayexec_execution/src/arrays/scalar/mod.rs
crates/rayexec_execution/src/arrays/storage/list.rs
crates/rayexec_execution/src/arrays/storage/untyped_null.rs
crates/rayexec_execution/src/execution/operators/unnest.rs
crates/rayexec_execution/src/functions/aggregate/builtin/first.rs
crates/rayexec_execution/src/functions/aggregate/builtin/minmax.rs
crates/rayexec_execution/src/functions/table/builtin/system.rs

chore: Add array buffer on top of raw buffer

---

crates/rayexec_execution/src/arrays/array/array_data.rs
crates/rayexec_execution/src/arrays/array/mod.rs

chore: Add array data wrapper around array buffer

---

crates/rayexec_execution/src/arrays/array/mod.rs
crates/rayexec_execution/src/arrays/array/physical_type.rs
crates/rayexec_execution/src/arrays/array/string_view.rs
crates/rayexec_execution/src/arrays/compute/cast/array.rs
crates/rayexec_execution/src/arrays/datatype.rs
crates/rayexec_execution/src/arrays/executor/scalar/fill.rs
crates/rayexec_execution/src/arrays/testutil.rs
crates/rayexec_execution/src/functions/aggregate/builtin/first.rs
crates/rayexec_execution/src/functions/aggregate/builtin/minmax.rs
crates/rayexec_execution/src/functions/scalar/builtin/comparison.rs

Split out from mutable array stuff

chore: Add more array methods

---

.gitignore
crates/glaredb/src/main.rs
crates/glaredb_execution/src/shell/debug.rs
crates/glaredb_execution/src/shell/lineedit.rs
crates/glaredb_execution/src/shell/raw.rs
crates/glaredb_execution/src/shell/shell.rs
crates/glaredb_wasm/src/shell.rs

fix: Fix extra line render in shell (and remove history)

---

crates/ext_tpch_gen/src/functions/table_gen.rs
crates/glaredb_execution/src/execution/operators/nested_loop_join/match_tracker.rs
crates/glaredb_execution/src/execution/operators/nested_loop_join/mod.rs
crates/glaredb_execution/src/functions/mod.rs
crates/glaredb_execution/src/functions/table/builtin/list_databases.rs
crates/glaredb_execution/src/functions/table/builtin/list_entries.rs
crates/glaredb_execution/src/functions/table/builtin/list_schemas.rs
crates/glaredb_execution/src/functions/table/builtin/memory_scan.rs
crates/glaredb_execution/src/functions/table/scan.rs

Plus some semi join stuff I guess

chore: Tweak async bind sig for table scan functions

---

crates/glaredb_execution/src/arrays/format/pretty/table.rs

Doesn't quite address https://github.com/GlareDB/glaredb/issues/3467 though.
```
glaredb> select 'hello
... world';
┌────────────┐
│ ?column?   │
│ Utf8       │
├────────────┤
│ hello    + │
│ world      │
└────────────┘
glaredb> select a, repeat(a, 3), b from values ('hello
... world', 5), ('te
... st
... in
... g', 6) v(a, b);
┌────────────┬────────────────────────────────┬───────┐
│ a          │ repeat                         │ b     │
│ Utf8       │ Utf8                           │ Int32 │
├────────────┼────────────────────────────────┼───────┤
│ hello    + │ hello                        + │     5 │
│ world      │ worldhello                   + │       │
│            │ worldhello                   + │       │
│            │ world                          │       │
│ te       + │ te …
```

feat: Slightly cleaner display of newlines in pretty tables

---

.github/workflows/ci.yaml
Cargo.lock
crates/glaredb_slt/Cargo.toml
crates/glaredb_slt/src/lib.rs

```
$ DEBUG_PRINT_EXPLAIN=1 DEBUG_PRINT_PROFILE=1 DEBUG_SET_PARTITIONS=1 cargo test lateral_join.slt
...
---- EXPLAIN ----
SELECT * FROM (VALUES ('aaa'), ('bbb')) v1(c1),
LATERAL (SELECT c1, c2 FROM (VALUES ('ccc'), ('ddd')) v2(c2))
ORDER BY 1, 2, 3;
┌───────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ plan_type │ plan                                                                                                                                          │
│ Utf8      │ Utf8                                                                                                                                          │
├───────────┼────────────────────────────────────────────────────────────── …
```

chore: Add back debug print profile for SLTs

---

crates/glaredb_execution/src/arrays/datatype.rs
crates/glaredb_execution/src/arrays/scalar/decimal.rs
crates/glaredb_execution/src/expr/mod.rs
crates/glaredb_execution/src/functions/implicit.rs
crates/glaredb_execution/src/functions/scalar/builtin/arith/add.rs
crates/glaredb_execution/src/functions/scalar/builtin/arith/decimal_sigs.rs
crates/glaredb_execution/src/functions/scalar/builtin/arith/mul.rs
crates/glaredb_execution/src/functions/scalar/builtin/arith/sub.rs
slt/standard/aggregates/functions/sum.slt
slt/standard/aggregates/having.slt
slt/standard/functions/scalars/decimal_comparison.slt

fix: Be stricter about implicit decimal casts

---

crates/glaredb_execution/src/arrays/sort/sorted_block.rs
slt/standard/order/order_by_many.slt

Also fixes the grouping.slt file.

fix: Fix some logic with order by ties

---

crates/glaredb_execution/src/arrays/array/array_buffer.rs
crates/glaredb_execution/src/arrays/array/mod.rs
crates/glaredb_execution/src/arrays/array/physical_type.rs
crates/glaredb_execution/src/arrays/compute/copy.rs
crates/glaredb_execution/src/arrays/compute/make_list.rs
crates/glaredb_execution/src/arrays/datatype.rs
crates/glaredb_execution/src/functions/candidate.rs
crates/glaredb_execution/src/functions/table/builtin/mod.rs
crates/glaredb_execution/src/functions/table/builtin/unnest.rs
crates/glaredb_execution/src/testutil/generate_batch.rs
scratch_queries/unnest.sql
slt/standard/functions/table/unnest_list.slt

Lateral not working yet, still needs list equality.

chore: Add back unnest table func

---

crates/glaredb_execution/src/arrays/batch.rs
crates/glaredb_execution/src/arrays/collection/equal.rs
crates/glaredb_execution/src/arrays/collection/mod.rs

chore: Check collection equality function

---

Cargo.lock
crates/ext_tpch_gen/Cargo.toml
crates/ext_tpch_gen/src/functions/customer.rs
crates/ext_tpch_gen/src/functions/lineitem.rs
crates/ext_tpch_gen/src/functions/mod.rs
crates/ext_tpch_gen/src/functions/nation.rs
crates/ext_tpch_gen/src/functions/orders.rs
crates/ext_tpch_gen/src/functions/part.rs
crates/ext_tpch_gen/src/functions/partsupp.rs
crates/ext_tpch_gen/src/functions/region.rs
crates/ext_tpch_gen/src/functions/supplier.rs
slt/tpch_gen/describe.slt
slt/tpch_gen/linitem.slt
slt/tpch_gen/orders.slt

```
glaredb> .maxrows 10
glaredb> select * from tpch_gen.lineitem(1);
┌────────────┬───────────┬───────────┬──────────────┬────────────┬─────────────────┬───┬──────────────┬───────────────┬────────────────┬────────────┬────────────┐
│ l_orderkey │ l_partkey │ l_suppkey │ l_linenumber │ l_quantity │ l_extendedprice │ … │ l_commitdate │ l_receiptdate │ l_shipinstruct │ l_shipmode │ l_comment  │
│ Int64      │ Int64     │ Int64     │ Int32        │ Int64      │ Decimal64(15,2) │   │ Date32       │ Date32        │ Utf8           │ Utf8       │ Utf8       │
├────────────┼───────────┼───────────┼──────────────┼────────────┼─────────────────┼───┼──────────────┼───────────────┼────────────────┼────────────┼────────────┤
│          1 │    155190 │      7706 │            1 │         17 │ …
```

chore: Update tpchgen-rs to 0.1.0

---

crates/glaredb_core/src/functions/table/builtin/list_entries.rs

```
glaredb> select * from list_functions();
┌───────────────┬─────────────┬───────────────┬───────────────┬────────────┬────────────────┬─────────────┬─────────────────────────────────┬─────────┬────────────────┐
│ database_name │ schema_name │ function_name │ function_type │ arguments  │ argument_types │ return_type │ description                     │ example │ example_output │
│ Utf8          │ Utf8        │ Utf8          │ Utf8          │ List[Utf8] │ List[Utf8]     │ Utf8        │ Utf8                            │ Utf8    │ Utf8           │
├───────────────┼─────────────┼───────────────┼───────────────┼────────────┼────────────────┼─────────────┼─────────────────────────────────┼─────────┼────────────────┤
│ system        │ spark       │ csc           │ scalar        │ [value]    │ …
```

feat: Add `arguments` col to `list_functions`

---

crates/docgen/src/main.rs
crates/docgen/src/markdown_table.rs
crates/docgen/src/section.rs
crates/docgen/src/session.rs
docs/reference/functions/numeric.md
docs/reference/functions/string.md

chore: Generate some function reference docs

---

crates/glaredb_core/src/config/session.rs
crates/glaredb_core/src/engine/query_result.rs
crates/glaredb_core/src/engine/session.rs
crates/glaredb_core/src/logical/binder/bind_context.rs
crates/glaredb_core/src/logical/binder/bind_query/bind_select.rs
crates/glaredb_core/src/logical/binder/bind_query/select_expr_expander.rs
crates/glaredb_core/src/logical/binder/bind_statement.rs
crates/glaredb_core/src/logical/binder/constant_binder.rs
slt/standard/vars/set_var.slt
slt/standard/vars/verify_optimized_plan.slt

Compares the output of an optimized plan with its unoptimized counterpart.

feat: Add `verify_optimized_query` session var

---

.github/workflows/ci.yaml

chore: Remove upload to coveralls

---

Cargo.lock
crates/glaredb_wasm/Cargo.toml
crates/glaredb_wasm/src/session.rs
docs/extensions/tpch.md

feat: Include tpchgen by default for wasm

---

crates/ext_csv/src/functions/read_csv.rs
crates/ext_csv/src/reader.rs
crates/ext_csv/src/schema.rs
crates/glaredb_core/src/execution/operators/scan.rs
slt/csv/small_batch_size.slt
slt/csv/userdata1.slt
slt/standard/read_csv.slt

Closes https://github.com/GlareDB/glaredb/issues/3603

fix: Increase csv infer buf size, treat empty string as null, fix pending issue

---

crates/glaredb_http/src/handle.rs

- Outer loop (whatever is calling `poll_read`) should already have some mechanism for reading the entire buffer.
- Prevents registering an additional waker which may cause the pipeline to poll after complete.
Closes https://github.com/GlareDB/glaredb/issues/3617

fix: Don't special-case stream Pending for http handle

---

.github/workflows/release.yaml
scripts/notarize_macos.sh

Closes https://github.com/GlareDB/glaredb/issues/3661

chore: Notarize mac binary

---

Cargo.lock
crates/glaredb_python/Cargo.toml
crates/glaredb_python/src/event_loop.rs
crates/glaredb_python/src/session.rs

Also remove a static tokio runtime.

chore: Compile in some extensions for python

---

crates/glaredb_core/src/logical/binder/bind_query/bind_select_list.rs
slt/standard/cast/decimal.slt
slt/standard/cast/integer_minmax.slt
slt/standard/cast/reference_through_cast.slt
slt/standard/cast/unsigned_int.slt

I actually just did this so I could do another release real quick

feat: Allow referencing CASTed columns with original name

---

crates/glaredb_core/src/logical/binder/bind_query/bind_from.rs
crates/glaredb_core/src/logical/binder/constant_binder.rs
crates/glaredb_core/src/logical/binder/expr_binder.rs
crates/glaredb_core/src/logical/resolver/expr_resolver.rs
crates/glaredb_core/src/logical/resolver/mod.rs
crates/glaredb_parser/src/ast/expr.rs
crates/glaredb_parser/src/ast/from.rs
slt/standard/functions/star_is_special.slt

Closes https://github.com/GlareDB/glaredb/issues/3683

fix: Handle star arguments better

---

crates/glaredb_wasm/Cargo.toml
crates/glaredb_wasm/src/shell.rs

fix: Handle paste on rust side for wasm

---

crates/glaredb_core/src/arrays/array/mod.rs
crates/glaredb_core/src/arrays/collection/chunk.rs
crates/glaredb_core/src/arrays/compute/copy.rs
crates/glaredb_core/src/arrays/compute/make_list.rs
crates/glaredb_core/src/testutil/generate_batch.rs

chore: Support constructing list arrays through `generate_array!`

---

.github/workflows/ci.yaml
crates/glaredb/src/main.rs
scripts/ci_run_cli_non_interactive.sh

Closes https://github.com/GlareDB/glaredb/issues/3654

chore: Try running CLI non-interactively in CI

---

crates/ext_parquet/src/schema/convert.rs

fix: Use smaller decimal size when reading decimal logical types

---

.gitignore
crates/glaredb_core/src/functions/cast/builtin/to_date.rs
crates/glaredb_core/src/logical/binder/bind_context.rs
crates/glaredb_core/src/optimizer/column_prune.rs
slt/clickbench/describe.slt
slt/clickbench/q06.slt
slt/clickbench/q23.slt
slt/clickbench/q36.slt
slt/clickbench/q37.slt
slt/clickbench/q38.slt
slt/clickbench/q39.slt
slt/clickbench/q40.slt
slt/clickbench/q41.slt
slt/clickbench/q42.slt
slt/standard/cast/date.slt
slt/standard/select/replace_different_types.slt
test_bin/integration_slt.rs

Closes https://github.com/GlareDB/glaredb/issues/3735

feat: Add int to date32 casts

---

crates/glaredb_core/src/arrays/sort/binary_merge.rs
slt/clickbench/q18.slt
slt/clickbench/q32.slt
slt/clickbench/q33.slt
slt/clickbench/q34.slt

Closes https://github.com/GlareDB/glaredb/issues/3733

fix: Fix binary merge panic

---

crates/glaredb_core/src/optimizer/column_prune.rs
slt/standard/aggregates/aggregate_with_no_column_refs.slt

Closes https://github.com/GlareDB/glaredb/issues/3743

fix: Allow column pruning with no column refs, remove empty projections

---

crates/glaredb_core/src/expr/physical/conjunction_expr.rs
crates/glaredb_core/src/expr/physical/evaluator.rs
crates/glaredb_core/src/expr/physical/mod.rs
crates/glaredb_core/src/expr/physical/planner.rs
crates/glaredb_core/src/expr/physical/selection_evaluator.rs
crates/glaredb_core/src/functions/documentation.rs
crates/glaredb_core/src/functions/scalar/builtin/debug.rs
crates/glaredb_core/src/functions/scalar/builtin/mod.rs
crates/glaredb_core/src/functions/scalar/builtin/not_implemented.rs
crates/glaredb_core/src/functions/scalar/builtin/struct_funcs.rs
crates/glaredb_core/src/logical/binder/bind_context.rs
crates/glaredb_core/src/logical/operator.rs
crates/glaredb_core/src/optimizer/mod.rs
crates/glaredb_core/src/optimizer/selection_reorder.rs

- Short-circuit evaluation of conjunction predicates in filters.
- Optimizer rule for reordering of conjunction filter predicates to take advantage of short-circuiting.
Before:
```
glaredb> SELECT SearchPhrase, MIN(URL), COUNT(*) AS c FROM hits WHERE URL LIKE '%google%' AND Searc
... hPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;
┌────────────────────────────────┬────────────────────────────────────────────────────────┬───────┐
│ SearchPhrase                   │ min                                                    │ c     │
│ Utf8                           │ Utf8                                                   │ Int64 │
├────────────────────────────────┼────────────────────────────────────────────────────────┼───────┤
│ прокур горбуши                 │ …
```

perf: Short-circuit selection evaluation

---

crates/glaredb_core/src/execution/operators/values.rs
crates/glaredb_core/src/execution/planner/plan_magic_scan.rs
slt/standard/subqueries/correlated_set_semantics.slt

Closes https://github.com/GlareDB/glaredb/issues/3621

fix: Ensure correlated subqueries (join) have set semantics

---

crates/glaredb_core/src/runtime/filesystem/directory.rs
crates/glaredb_core/src/runtime/filesystem/glob.rs
crates/glaredb_core/src/runtime/filesystem/memory.rs
crates/glaredb_core/src/runtime/filesystem/mod.rs
crates/glaredb_http/src/filesystem.rs
crates/glaredb_http/src/gcs/filesystem.rs
crates/glaredb_http/src/s3/directory.rs
crates/glaredb_http/src/s3/filesystem.rs
crates/glaredb_http/src/s3/list.rs
crates/glaredb_http/src/s3/mod.rs
crates/glaredb_rt_native/src/filesystem.rs
crates/glaredb_wasm/src/origin_filesystem.rs
slt/s3/public/glob.slt

GCS & polish next.
```
glaredb> SELECT * FROM glob('s3://glaredb-public/testdata/csv/glob_numbers/*.csv') ORDER BY 1;
┌───────────────────────────────────────────────────────┐
│ filename                                              │
│ Utf8                                                  │
├───────────────────────────────────────────────────────┤
│ s3://glaredb-public/testdata/csv/glob_numbers/100.csv │
│ s3://glaredb-public/testdata/csv/glob_numbers/200.csv │
│ s3://glaredb-public/testdata/csv/glob_numbers/300.csv │
│ s3://glaredb-public/testdata/csv/glob_numbers/400.csv │
│ s3://glaredb-public/testdata/csv/glob_numbers/500.csv │
└───────────────────────────────────────────────────────┘
```

feat: Initial S3 globbing

---

crates/glaredb_core/src/runtime/filesystem/directory.rs
crates/glaredb_http/src/gcs/directory.rs
crates/glaredb_http/src/gcs/filesystem.rs
crates/glaredb_http/src/gcs/list.rs
crates/glaredb_http/src/gcs/mod.rs
crates/glaredb_http/src/lib.rs
crates/glaredb_http/src/list.rs
crates/glaredb_http/src/s3/directory.rs
slt/gcs/public/glob.slt

```
glaredb> SELECT * FROM glob('gs://glaredb-public/testdata/csv/glob_numbers/*.csv') ORDER BY 1;
┌───────────────────────────────────────────────────────┐
│ filename                                              │
│ Utf8                                                  │
├───────────────────────────────────────────────────────┤
│ gs://glaredb-public/testdata/csv/glob_numbers/100.csv │
│ gs://glaredb-public/testdata/csv/glob_numbers/200.csv │
│ gs://glaredb-public/testdata/csv/glob_numbers/300.csv │
│ gs://glaredb-public/testdata/csv/glob_numbers/400.csv │
│ gs://glaredb-public/testdata/csv/glob_numbers/500.csv │
└───────────────────────────────────────────────────────┘
```

feat: Initial GCS globbing

---

crates/glaredb_core/src/runtime/filesystem/mod.rs
crates/glaredb_http/src/gcs/filesystem.rs
crates/glaredb_http/src/list.rs
slt/gcs/private/glob.slt
slt/s3/private/glob.slt

Closes https://github.com/GlareDB/glaredb/issues/3798

fix: Handle gcs token fetching during fs state load

---

crates/glaredb_core/src/engine/session.rs
crates/glaredb_core/src/execution/operators/hash_join/mod.rs
crates/glaredb_core/src/execution/operators/materialize.rs
crates/glaredb_core/src/execution/planner/mod.rs
crates/glaredb_core/src/execution/planner/plan_explain.rs
crates/glaredb_core/src/explain/formatter.rs
crates/glaredb_core/src/explain/node.rs
crates/glaredb_core/src/logical/binder/bind_context.rs
crates/glaredb_core/src/logical/logical_explain.rs
crates/glaredb_core/src/logical/planner/plan_explain.rs
slt/standard/explain.slt

No materializations:
```sql
EXPLAIN WITH c1(a) AS (SELECT random()),
c2(b) AS (SELECT a + 2 FROM c1)
SELECT * FROM c1, c2;
```
```
┌───────────┬──────────────────────────────────────────────────────────────────────────────────────────┐
│ plan_type │ plan                                                                                     │
│ Utf8      │ Utf8                                                                                     │
├───────────┼──────────────────────────────────────────────────────────────────────────────────────────┤
│ unoptimi… │ Base                                                                                   + │
│           │   Project                                                                              + │
│           │     ├ location: Any …
```

feat: Clearly labeled materializations in explain

---

crates/ext_parquet/src/column/struct_reader.rs
crates/ext_parquet/src/column/value_reader/primitive.rs
slt/parquet/firebolt_ecommerce_sample.slt

Fixes https://github.com/GlareDB/glaredb/issues/3837

fix: Support reading physical INT64 as timestamp micros (parquet)

---

crates/glaredb_rt_native/src/threaded/task.rs
crates/glaredb_wasm/src/runtime.rs

Just use the task state directly.
Does not yet handle spurious wakeups.

chore: Remove separate waker structs

---

crates/glaredb_core/src/functions/aggregate/builtin/approx_count_distinct.rs
crates/glaredb_core/src/functions/aggregate/builtin/approx_quantile.rs
crates/glaredb_core/src/functions/aggregate/builtin/mod.rs
crates/glaredb_core/src/statistics/mod.rs
crates/glaredb_core/src/statistics/tdigest.rs
slt/standard/functions/aggregate/approx_quantile.slt

```
glaredb> SELECT 
... approx_quantile(a, .75)
...   FROM generate_series(1, 100) g(a), (VALUES (1), (2), (3));
┌─────────────────┐
│ approx_quantile │
│ Float64         │
├─────────────────┤
│           75.75 │
└─────────────────┘
```

feat: `approx_quantile` aggregate function

---

crates/ext_iceberg/src/extension.rs
crates/ext_iceberg/src/functions/metadata.rs
crates/ext_iceberg/src/table/spec/manifest.rs
slt/iceberg/iceberg_data_files.slt

```
glaredb> SELECT *
... FROM iceberg_data_files('./testdata/iceberg/tables-v2/lineitem_versioned');
┌────────┬─────────┬────────────────────────────────────────────────────────────┬─────────────┬──────────────┐
│ status │ content │ file_path                                                  │ file_format │ record_count │
│ Utf8   │ Utf8    │ Utf8                                                       │ Utf8        │ Int64        │
├────────┼─────────┼────────────────────────────────────────────────────────────┼─────────────┼──────────────┤
│ ADDED  │ DATA    │ iceberg/tables-v2/lineitem_versioned/data/00000-7-e5c4c12… │ PARQUET     │         1000 │
│ ADDED  │ DATA    │ iceberg/tables-v2/lineitem_versioned/data/00000-6-1f2f0cb… │ PARQUET     │         1000 │ …
```

feat: `iceberg_data_files` function
