GlareDB/glaredb

Cargo.lock, crates/glaredb/Cargo.toml, crates/glaredb/src/bin/main.rs, crates/glaredb/src/local.rs
New `mode` option for specify output formatting:
```
--mode <MODE>
Display output mode
[default: table]
[possible values: table, json, ndjson, csv]
```
Table (default):
```
% ./glaredb local --query "select * from (values (1, 'hello'), (2, 'world'), (3, '!'))"
+---------+---------+
| column1 | column2 |
+---------+---------+
| 1       | hello   |
| 2       | world   |
| 3       | !       |
+---------+---------+
```
Json:
```
% ./glaredb local --mode json --query "select * from (values (1, 'hello'), (2, 'world'), (3, '!'))"
[{"column1":1,"column2":"hello"},
{"column1":2,"column2":"world"},
{"column1":3,"column2":"!"}]
```
This can also be set during interactive sessions:
```
% ./glaredb local
GlareDB (v0.0.11)
> \help
\help           Show this help text
\mode MODE …
```
=> feat: Add local client commands to specify output formatting

crates/datasources/src/object_store/errors.rs, crates/datasources/src/object_store/gcs.rs, crates/datasources/src/object_store/s3.rs, crates/metastore/proto/options.proto, crates/metastore/src/types/options.rs, crates/sqlexec/src/planner/session_planner.rs
Closes https://github.com/GlareDB/glaredb/issues/991
```
~/Code/github.com/glaredb/glaredb [2] % cargo run --bin glaredb -- local
Finished dev [unoptimized + debuginfo] target(s) in 0.58s
Running `target/debug/glaredb local`
GlareDB (v0.0.11)
> create external table v from gcs options (location = 'tyrell/voight_kampff.csv', bucket='glaredb-demos');
create table
> select * from v limit 10;
+--------------------------------------+---------------------+--------------------+-----------------+------------------+------------+
| Test_ID                              | Examiner_Name       | Subject_Name       | Questions_Asked | Final_Assessment | Test_Date  |
+--------------------------------------+---------------------+--------------------+-----------------+--------------- …
```
=> feat: Make gcs and s3 credentials optional

.github/workflows/ci.yaml, crates/testing/tests/sqllogictests/hooks.rs
Hopefully this will let us narrow down why these tests occasionally fail. Right now all the logs are intermingled so hard to see what's what.
Also reduces container start timeout to 30s since that should be more than enough time.
=> chore: Run ssh tunnel tests separately

crates/glaredb/src/bin/main.rs
Now `--version` will just return the version specified in the root Cargo.toml.
=> chore: Remove setting version to "pre-release"

Cargo.lock, crates/datafusion_planner/Cargo.toml, crates/datafusion_planner/src/planner.rs, crates/datafusion_planner/src/relation/mod.rs, crates/datasources/Cargo.toml, crates/datasources/src/common/listing.rs, crates/metastore/Cargo.toml, crates/metastore/src/builtins.rs, crates/metastore/src/database.rs, crates/metastore/src/errors.rs, crates/metastoreproto/proto/catalog.proto, crates/metastoreproto/src/types/catalog.rs, crates/sqlbuiltins/Cargo.toml, crates/sqlbuiltins/src/errors.rs, crates/sqlbuiltins/src/functions.rs, crates/sqlbuiltins/src/lib.rs, crates/sqlexec/src/planner/context_builder.rs, crates/sqlexec/src/planner/dispatch.rs, testdata/sqllogictests_bigquery/read.slt, testdata/sqllogictests_mongodb/read.slt, testdata/sqllogictests_mysql/read.slt, testdata/sqllogictests_postgres/read.slt, testdata/sqllogictests_postgres/read_postgres.slt, testdata/sqllogictests_snowflake/read.slt
Adds table returning functions that allow for reading from external data
sources. These are meant to be used as an alternative to `CREATE EXTERANL
TABLE/DATABASE ...`.
What this looks like:
``` sql
select * from read_postgres('postgres://postgres:postgres@localhost/postgres', 'public', 'users)
```
These functions can be used anywhere in a query where a table identifier would
be used.
The list of supported functions can be found by querying the
`glare_catalog.functions` table:
``` text
> select function_name, function_type from glare_catalog.functions;
+----------------+---------------+
| function_name  | function_type |
+----------------+---------------+
| read_mongodb   | table         |
| read_mysql     | table         |
| read_bigquery  | table         |
| read_snowflake | table …
```
=> feat: Add functions for reading data sources

Cargo.lock, crates/glaredb/Cargo.toml, crates/glaredb/src/highlighter.rs, crates/glaredb/src/lib.rs, crates/glaredb/src/local.rs, crates/glaredb/src/prompt.rs, crates/sqlexec/src/lib.rs
adds support for the following to the cli: 
- syntax highlighting,  
- multiline support  _(as is common with other sql interfaces.)_ 
- history autofill
partially closes https://github.com/GlareDB/glaredb/issues/1090
=> feat(cli): add highlighting & multiline sql support

crates/glaredb/src/bin/main.rs, crates/glaredb/src/server.rs, crates/pgsrv/src/auth.rs, crates/pgsrv/src/codec/server.rs, crates/pgsrv/src/handler.rs, crates/pgsrv/src/messages.rs
A bit of hack (since compliant frontends shouldn't send auth messages after AuthenticationOk), but should help with internal development.
```
glaredb server --ignore-auth
```
=> chore: Allow ignoring auth messages

crates/glaredb/src/local.rs, crates/metastore/src/builtins.rs, crates/metastore/src/database.rs, crates/metastore/src/errors.rs, crates/metastore/src/validation.rs, crates/metastoreproto/proto/catalog.proto, crates/metastoreproto/proto/options.proto, crates/metastoreproto/proto/service.proto, crates/metastoreproto/src/session.rs, crates/metastoreproto/src/types/catalog.rs, crates/metastoreproto/src/types/options.rs, crates/metastoreproto/src/types/service.rs, crates/pgsrv/src/handler.rs, crates/pgsrv/src/proxy.rs, crates/sqlexec/src/context.rs, crates/sqlexec/src/engine.rs, crates/sqlexec/src/errors.rs, crates/sqlexec/src/parser.rs, crates/sqlexec/src/planner/dispatch.rs, crates/sqlexec/src/planner/errors.rs, crates/sqlexec/src/planner/logical_plan.rs, crates/sqlexec/src/planner/session_planner.rs, crates/sqlexec/src/session.rs, testdata/sqllogictests/credentials.slt, testdata/sqllogictests/drop.slt, testdata/sqllogictests/object_names.slt, testdata/sqllogictests_bigquery/credentials.slt, testdata/sqllogictests_object_store/gcs/credentials.slt, testdata/sqllogictests_object_store/s3/credentials.slt
```
CREATE CREDENTIALS debug_creds
PROVIDER debug
OPTIONS (table_type = 'never_ending');
CREATE EXTERNAL TABLE debug_table
FROM debug
CREDENTIALS debug_creds;
DROP CREDENTIALS debug_creds;
```
Internal catalog:
```
〉select * from glare_catalog.credentials;
+-------+------------------+---------+----------+----------------+
| oid   | credentials_name | builtin | provider | comment        |
+-------+------------------+---------+----------+----------------+
| 20000 | aws_creds        | false   | aws      | test aws creds |
+-------+------------------+---------+----------+----------------+
```
Fixes https://github.com/GlareDB/glaredb/issues/1126, https://github.com/GlareDB/glaredb/issues/1141, https://github.com/GlareDB/glaredb/issues/1142
=> feat: Add support for credentials objects

crates/datasources/Cargo.toml, crates/datasources/src/object_store/errors.rs, crates/datasources/src/object_store/http.rs, crates/datasources/src/object_store/mod.rs, crates/sqlbuiltins/src/functions.rs
closes #1098 
note: this is currently limited to `parquet` for a single file. 
Todo: 
- add support for an array of files `parquet_scan([...])`
=> feat: add "parquet_scan" function

crates/datasources/src/bigquery/mod.rs
The `all` option means return all data sets, including hidden ones. I believe it was put in originally with the intent to not paginate. However, `list` won't paginate any ways.
Closes https://github.com/GlareDB/glaredb/issues/1161
=> fix: Don't return hidden data sets from bigquery

Cargo.lock, Cargo.toml, crates/datasources/Cargo.toml, crates/datasources/src/object_store/gcs.rs, crates/datasources/src/object_store/http.rs, crates/datasources/src/object_store/local.rs, crates/datasources/src/object_store/mod.rs, crates/datasources/src/object_store/s3.rs, crates/sqlbuiltins/Cargo.toml, crates/sqlbuiltins/src/functions.rs, crates/sqlexec/src/planner/dispatch.rs
follow up from #1160. 
in addition to the `http`/`https` schemes, we also support `file://`
```sql
select * from parquet_scan('file://path/to/file.parquet');
```
=> add support for reading from "file://" for `parquet_scan`

crates/datasources/src/native/access.rs, crates/datasources/src/native/insert.rs, crates/datasources/src/native/mod.rs, testdata/sqllogictests/table.slt, testdata/sqllogictests_native/basic.slt
Closes https://github.com/GlareDB/glaredb/issues/1150
No longer buffering in memory.
When timestamps are properly supported in create tables (see https://github.com/GlareDB/glaredb/issues/1157), we can reuse a lot of our existing slt stuff to add tests for this.
=> feat: Stream writes to tables

crates/datasources/src/native/access.rs
=> chore: Remove native table inner

crates/datasources/src/object_store/http.rs, crates/sqlbuiltins/src/functions.rs
can now read from csv''s both locally & remotely
```
〉select * from csv_scan('https://path/to/file.csv');
〉select * from csv_scan('file://path/to/file.csv');
```
=> feat: add "csv_scan" function

crates/metastore/src/srv.rs
This happens rarely, and corresponds to redeploys of metastore. After some time, it does fix itself.
The fix is to fallback to loading the catalog from storage if it's not in the map. But before doing that, I think we should look at how we want to evict catalogs, because implementing that would solve this issue too.
The logging is really there to tell us how often this happens.
=> chore: Log error if failed to find catalog

.github/workflows/release.yaml, CONTRIBUTING.md, crates/datasources/Cargo.toml, crates/datasources/src/common/errors.rs, crates/datasources/src/common/ssh/key.rs, crates/datasources/src/common/ssh/mod.rs, crates/datasources/src/common/ssh/session.rs, crates/datasources/src/mysql/errors.rs, crates/datasources/src/mysql/mod.rs, crates/datasources/src/postgres/errors.rs, crates/datasources/src/postgres/mod.rs, crates/sqlexec/src/planner/dispatch.rs, crates/sqlexec/src/planner/errors.rs, crates/sqlexec/src/planner/session_planner.rs, xtask/src/main.rs, xtask/src/target.rs
- Closes #1030
- Closes #1053
Add windows builds to the release yaml. 
To accomplish this, we need to conditionally compile in openssh, which impacts the ssh tunnels feature. On linux and mac, this continues to work as expected, while the windows code path will always return an error when attempting to create a tunnel.
This required a small amount of refactoring, and I tried to keep the conditional compilation to a single file. I also needed to tweak the cargo.toml to avoid pulling openssh if we're building on a platform that it doesn't support.
Conditional compilation is currently based on checking the target os, and not on adding a cargo feature. Longer term, we may want to put ssh tunnels behind its own flag, and enable/disable depending on the platform we're building for. I opted not …
=> feat: Windows builds

Dockerfile
#1198 made it so we no longer need this in our dockerfile.
=> remove python dep from docker

py-glaredb/examples/pandas_interop.py, py-glaredb/src/environment.rs, py-glaredb/src/session.rs
Adds support for reading and writing to pandas data frames.
```python
import glaredb
import pandas as pd
df = pd.DataFrame(
{
"A": [1, 2, 3, 4, 5],
"fruits": ["banana", "banana", "apple", "apple", "banana"],
"B": [5, 4, 3, 2, 1],
"cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
}
)
con = glaredb.connect("/tmp/testing")
df = con.sql("select * from df where fruits = 'banana'").to_pandas();
print(df)
```
Output:
```
A  fruits  B    cars
0  1  banana  5  beetle
1  2  banana  4    audi
2  5  banana  1  beetle
```
=> feat: Add pandas support

py-glaredb/examples/multiple.py, py-glaredb/examples/pandas_interop.py, py-glaredb/examples/polars_interop.py, py-glaredb/src/lib.rs, py-glaredb/src/session.rs
If provided, both table storage and metastore storage will write to this directory. Otherwise, everything will be in memory.
Also sets up spill path too.
=> feat: Make data dir optional in python bindings

testdata/sqllogictests/functions/csv_scan.slt
Fixes https://github.com/GlareDB/glaredb/issues/1208
=> chore: Use raw github link in csv_scan test

Dockerfile
Newer versions of `half` require 1.70 (which we're not using yet, but we'll likely need to bump it soon anyways).
=> chore: Bump rust version in docker image

Cargo.lock, crates/pgprototest/Cargo.toml
0.7.0 introduced bahvior around outputs ending with newlines. Specifically, if an output did not end with a newline, datadriven would add extra dashes around the output along with "no newline" text. Unfortunately, this behavior made the tests hard to read.
Adding just "\n" as the output didn't work as expected, since each test rewrite would add an additional newline to the output.
Downgrading seems like the best solution for the time being.
=> fix: Downgrade datadriven crate

crates/sqlexec/src/planner/logical_plan.rs, testdata/sqllogictests/explain.slt
Datafusion's `from_plan` function will error/panic if provided a logical plan for EXPLAIN/EXPLAIN ANALYZE alongside an empty expression list. This gets called when replacing paramters for query. Since we go through the prepare/bind/execute phases even for queries that don't have paramters, we would reach this every time.
The conditional check just pulls out the inner logical plan and replaces parameters for that.
```
% cargo run --bin glaredb -- local --query "explain select 1;"
Finished dev [unoptimized + debuginfo] target(s) in 0.46s
Running `target/debug/glaredb local --query 'explain select 1;'`
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | …
```
=> fix: Fix explain queries

crates/datasources/src/common/errors.rs, crates/datasources/src/common/mod.rs, crates/datasources/src/common/sink/csv.rs, crates/datasources/src/common/sink/json.rs, crates/datasources/src/common/sink/mod.rs, crates/datasources/src/common/sink/parquet.rs, crates/datasources/src/object_store/gcs.rs, crates/datasources/src/object_store/local.rs, crates/datasources/src/object_store/s3.rs, crates/metastore/src/errors.rs, crates/metastore/src/lib.rs, crates/metastore/src/types.rs, crates/metastore/src/validation.rs, crates/pgsrv/src/handler.rs, crates/sqlexec/src/errors.rs, crates/sqlexec/src/parser.rs, crates/sqlexec/src/parser/options.rs, crates/sqlexec/src/planner/logical_plan.rs, crates/sqlexec/src/planner/session_planner.rs, crates/sqlexec/src/session.rs
=> feat: `COPY TO` support

.github/workflows/ci.yaml, .github/workflows/python-release.yaml, .github/workflows/release.yaml, CONTRIBUTING.md, Dockerfile, README.md, justfile, py-glaredb/justfile
closes #1238 
this replaces the xtask build tool with `just`
I havent replaced any of the commands in the ci or docs, wanted to confirm this looks good before doing so. 
what I think is nice about this approach is that just will auto inherit the parent justfile & you don't have to manage the working dir at all when running the scripts, unless otherwise specified, it'll always use the dir of the justfile. 
```sh
just fmt # runs `cargo fmt` from the root dir
just build # runs the build cmd from pwd
just fmt # runs the parent `fmt` from the parent's dir `/glaredb`
just build # runs the build cmd from pwd
```
it's also pretty easy to add subcommands
for example, this delegates all `python` commands to the subdir's justfile. 
```make
python cmd *args: protoc
just py-glaredb/{{cmd}} {{args}} …
```
=> refactor: xtask --> justfile

crates/sqlexec/src/planner/session_planner.rs
Still need to test it with `TIMESTAMPTZ` AND `TIME(TZ)` ...
Fixes #1157
=> fix: Allow create tables with timestamps

crates/pgsrv/src/auth.rs, crates/pgsrv/src/proxy.rs
Cloud can now target compute engines based on this option and will return the compute engine IP that matches the name when specified or otherwise will target the shared pool.
=> feat: support compute_engine authentication parameter

.github/workflows/ci.yaml, crates/datasources/src/common/errors.rs, crates/datasources/src/common/mod.rs, crates/datasources/src/common/url.rs, crates/datasources/src/object_store/gcs.rs, crates/datasources/src/object_store/local.rs, crates/datasources/src/object_store/registry.rs, crates/datasources/src/object_store/s3.rs, crates/metastore/src/types.rs, crates/sqlexec/src/planner/session_planner.rs, crates/testing/tests/sqllogictests/hooks.rs, justfile, testdata/sqllogictests_object_store/local/copy_to.slt
Example:
```
copy ( select * from glare_catalog.tables ) to
'gs://vrongmeal-public-test/mytestdata/pq.parquet' credentials gcp_creds;
```
Fixes #1260
Also support table as sources.
```
copy glare_catalog.tables to './local.csv';
```
Fixes #1261
=> feat: Support URLs for `COPY .. TO ..`.

.github/dependabot.yml
This pull request improves Dependabot configuration file and assigns @scsmithr for reviews before merge; The updates will be directed to the `cargo-conf` branch first, where they will undergo review befor getting merged into the main branch.
Dependabot will open a single pull request to update all cargo dependencies at the same time.
This pull request addresses issue #1281.
Please add the `dependencies` label to this repo as it will allow Dependabot to use it;  otherwise the generated pull requests wont have any labels.
=> chore: Add Dependabot configuration for Cargo

crates/datasources/src/common/url.rs, crates/datasources/src/object_store/mod.rs, crates/sqlbuiltins/src/errors.rs, crates/sqlbuiltins/src/functions.rs, crates/sqlexec/src/planner/context_builder.rs, crates/sqlexec/src/planner/session_planner.rs, justfile
2 Arguments:
```sql
SELECT * FROM csv_scan('gs://bucket/path/to/object.csv', 'gcp_creds');
```
3 Arguments:
```sql
SELECT * FROM parquet_scan(
's3://bucket/path/to/object.csv',
'aws_creds',
'us-east-1' -- Region
);
```
Fixes #1249
=> feat: Support object store in `*_scan` functions.

crates/pgsrv/src/auth.rs, crates/pgsrv/src/proxy.rs
Closes https://github.com/GlareDB/glaredb/issues/1312
=> fix: stop parsing datasource and tunnel limits from cloud response

.cargo/config.toml, crates/datafusion_planner/src/relation/mod.rs, crates/sqlbuiltins/src/errors.rs, crates/sqlbuiltins/src/functions.rs, testdata/sqllogictests_object_store/gcs/copy_to.slt, testdata/sqllogictests_object_store/s3/copy_to.slt
We can now add named arguments that can be passed into table functions which act like options basically.
Passing identifiers as arguments is also supported now.
```sql
SELECT * FROM csv_scan(
's3://bucket/object',
aws_creds,      -- Identifier, can also be quoted: "aws_creds"
region => '...' -- Named argument, can be passed as `key => val`
);
```
Fixes #1308, #1297 
---
=> feat: Support named arguments and idents in table functions.

.github/workflows/ci.yaml, crates/sqlbuiltins/src/errors.rs, crates/sqlbuiltins/src/functions.rs, justfile, testdata/sqllogictests/virtual_catalog.slt, testdata/sqllogictests_bigquery/external_database.slt, testdata/sqllogictests_mysql/external_database.slt, testdata/sqllogictests_postgres/external_database.slt, testdata/sqllogictests_snowflake/external_database.slt
Can only specify identifiers as parameters when required. For example:
```sql
SELECT * FROM list_schemas( ext_db_name );
-- `Ident`s can be quoted.
SELECT * FROM list_tables( ext_db_name, "SchemaName" );
SELECT * FROM csv_scan( '<url>', creds_obj );
```
=> fix: Explicitly use `Ident` in table function parameters.

.cargo/config.toml
I removed this in another PR, didn't realize we're still using it for zipping.
=> fix: Add xtask alias back (for zip)

.github/ISSUE_TEMPLATE/planned-feature.md
1. Make lang of Impacts more clear (it's more about breaking systems or people)
2. Remove Tasks (we don't use it or rarely enough to justify)
3. Merge specs/sujmmary, since we rarely distinguish
=> chore: simplify feat template

crates/glaredb/src/local.rs, crates/pgsrv/src/handler.rs, crates/sqlexec/src/context.rs, crates/sqlexec/src/engine.rs, crates/sqlexec/src/functions.rs, crates/sqlexec/src/lib.rs, crates/sqlexec/src/metrics.rs, crates/sqlexec/src/session.rs, crates/sqlexec/src/vars.rs, py-glaredb/src/lib.rs
Adds read-only session variables, and moves a bunch of session configuration to `SessionVars`.
Moving session configuration to `SessionVars` provides the following benefits:
- Centralizes session configuration. This still _some_ amount of configuration not stored here, but we can work on moving stuff into this as needed.
- Allows users to inspect variables.
As a user, I can now view session limits (and more) via the `SHOW` command:
```sql
〉show memory_limit_bytes;
+--------------------+
| memory_limit_bytes |
+--------------------+
| None               |
+--------------------+
```
Attempting to set a read-only session var will error:
```sql
〉set memory_limit_bytes to 9999;
Error: Variable is readonly: memory_limit_bytes
```
This may be useful with …
=> feat: Read-only session vars

Cargo.lock, crates/glaredb/src/bin/main.rs, crates/glaredb/src/local.rs, crates/glaredb/src/server.rs, crates/sqlexec/Cargo.toml, crates/sqlexec/src/background_jobs.rs, crates/sqlexec/src/engine.rs, crates/sqlexec/src/errors.rs, crates/sqlexec/src/lib.rs, crates/testing/tests/sqllogictests/hooks.rs
We have a framework to setup backgound jobs. Jobs with the same name are batched together. Each job can set a time when they start and until the existing job has finished, a new job is not added.
Fixes #1167
=> feat: Support background jobs

.github/dependabot.yml
Well what if there's an incompatability with a dep?
=> chore: Remove dependabot grouping

crates/datasources/src/native/access.rs, crates/metastore/src/database.rs, crates/metastore/src/storage/persist.rs, crates/metastore_client/proto/catalog.proto, crates/metastore_client/proto/service.proto, crates/metastore_client/src/session.rs, crates/metastore_client/src/types/catalog.rs, crates/metastore_client/src/types/service.rs, crates/sqlbuiltins/src/builtins.rs, crates/sqlexec/src/background_jobs.rs, crates/sqlexec/src/background_jobs/storage.rs, crates/sqlexec/src/context.rs, crates/sqlexec/src/engine.rs, crates/sqlexec/src/metastore.rs, crates/sqlexec/src/planner/dispatch.rs, crates/sqlexec/src/session.rs
Runs a background job on `INSERT`s (with a batch delay of 5 minutes) for the deployment.
```
〉select * from glare_catalog.deployment_metadata;
+--------------+-------+
| key          | value |
+--------------+-------+
| storage_size | 3852  |
+--------------+-------+
```
Fixes #1155
=> feat: Add background job to track storage usage

CONTRIBUTING.md, scripts/prepare-testdata.sh
closes #1342
- The large datasets used for testing were made public & scripts updated accordingly
- `contributing.md` updated to clarify testing commands & dependencies.
=> chore: update prepare-tesdata script & contributing.md

crates/arrow_util/src/pretty.rs
closes #1420 
```sh
glaredb universalmind303/truncate-logic ≡34s 
λ just run local --max-rows 10  
GlareDB (v0.2.1)
〉select * from generate_series(1, 100000);
┌────────────────────────┐
│ generate_series        │
│ ──                     │
│ Int64                  │
╞════════════════════════╡
│ 1                      │
│ 2                      │
│ 3                      │
│ 4                      │
│ 5                      │
│ …                      │
│ 99997                  │
│ 99998                  │
│ 99999                  │
│ 100000                 │
│ ───                    │
│ 100000 rows (10 shown) │
└────────────────────────┘
〉
```
I did have one note. 
would you expect the continuation row to count towards the `max_rows`? 
like if i …
=> fix: error with truncate logic

crates/datafusion_ext/src/planner/select.rs, crates/sqlexec/src/parser.rs, testdata/sqllogictests/select.slt
```
〉select * exclude column1 from t1;
┌─────────┐
│ column2 │
│ ──      │
│ Int64   │
╞═════════╡
│ 2       │
└─────────┘
```
We already had it (given that we're using datafusion's planner), but sqlparser will only try to parse it for a hard-coded subset of dialects, and so I switched to `GenericDialect`.
=> feat: select exclude/except

Cargo.lock, py-glaredb/Cargo.toml, py-glaredb/src/session.rs
```
% ./.venv/bin/python3 examples/show.py
┌───────┬───────────┬───────┬───────────┐
│ A     │ fruits    │ B     │ cars      │
│ ──    │ ──        │ ──    │ ──        │
│ Int64 │ LargeUtf8 │ Int64 │ LargeUtf8 │
╞═══════╪═══════════╪═══════╪═══════════╡
│ 1     │ banana    │ 5     │ beetle    │
│ 2     │ banana    │ 4     │ audi      │
│ 5     │ banana    │ 1     │ beetle    │
└───────┴───────────┴───────┴───────────┘
┌───────┬────────┬───────┬────────┐
│ A     │ fruits │ B     │ cars   │
│ ──    │ ──     │ ──    │ ──     │
│ Int64 │ Utf8   │ Int64 │ Utf8   │
╞═══════╪════════╪═══════╪════════╡
│ 1     │ banana │ 5     │ beetle │
│ 2     │ banana │ 4     │ audi   │
│ 5     │ banana │ 1     │ beetle │
└───────┴────────┴───────┴────────┘
```
=> feat: Use pretty tables with `show` in python

crates/glaredb/src/prompt.rs
"〉" is actually pretty uncommon for fonts. We could go with "⟩" since it's typically preferred over "〉", but it still lacks support in some popular monospace fonts like Source Code Pro and Fira Mono.
As someone who likes to make everything "just right", I wouldn't like for a tool that I'm using to use a glyph not support by my font. And so a basic ">" seems like the most straightforward pick for the prompt character.
=> chore: Swap bracket character in prompt

crates/arrow_util/src/pretty.rs
closes #1440
So the logic is as follows. 
```mermaid
flowchart TD
A[Start] --> B{max_columns is Some?}
B -- Yes --> C[Use max_columns]
B -- No --> D{width is Some?}
D -- Yes --> E[Calculate avg_column_len]
D -- No --> F[Use DEFAULT_MAX_COLUMNS]
E --> G["Use inferred max columns (width - 10) / avg_column_len"]
```
=> fix: display correct number of columns based on terminal width

crates/datasources/src/object_store/mod.rs, crates/glaredb/src/server.rs, crates/metastore_client/proto/options.proto, crates/metastore_client/src/types/options.rs, crates/sqlexec/src/parser/options.rs, crates/sqlexec/src/planner/dispatch.rs, crates/sqlexec/src/planner/session_planner.rs, testdata/sqllogictests_object_store/gcs/copy_to_and_scan.slt, testdata/sqllogictests_object_store/local/copy_to_and_scan.slt, testdata/sqllogictests_object_store/s3/copy_to_and_scan.slt
```sql
CREATE EXTERNAL TABLE abc FROM gcs CREDENTIALS gcp_creds (
location 'some/path/**/to/file.csv',
-- Optional, if not provided, will be infered from location
file_type 'csv'
);
```
The change is minor. Found a bug out of the blue, previous code took the prefix for search as "abc" when querying glob pattern "abc*". Since object_store adds a "/", prefix in this case should be None. Fixed that too.
**TODO:**
=> feat: Support globbed location for external tables as well

crates/sqlexec/src/background_jobs.rs, crates/sqlexec/src/context.rs, crates/sqlexec/src/errors.rs, testdata/sqllogictests/temp_table.slt
```sql
create temp table abc as values (1, 2);
-- Valid table refs are:
-- * abc
-- * current_session.abc
-- * default.current_session.abc
drop table abc;
```
=> feat: Support drops for temp tables

crates/sqlexec/src/planner/session_planner.rs, testdata/sqllogictests/table.slt
**Without any alias/casting:**
```
> create table t1 as values (1, 2);
create table
> select * from t1;
┌─────────┬─────────┐
│ column1 │ column2 │
│ ──      │ ──      │
│ Int64   │ Int64   │
╞═════════╪═════════╡
│ 1       │ 2       │
└─────────┴─────────┘
```
**With alias/casting:**
```
> create table t2 (a int, b text) as values (1, 2);
create table
> select * from t2;
┌───────┬──────┐
│ a     │ b    │
│ ──    │ ──   │
│ Int32 │ Utf8 │
╞═══════╪══════╡
│ 1     │ 2    │
└───────┴──────┘
```
**With few columns aliased/cast:**
```
> create table t3 (a int) as values (1, 2);
create table
> select * from t3;
┌───────┬─────────┐
│ a     │ column2 │
│ ──    │ ──      │
│ Int32 │ Int64   │
╞═══════╪═════════╡
│ 1     │ 2       │
└───────┴─────────┘
```
Fixes #1425
=> feat: Support aliasing/casting in `CREATE TABLE .. AS ..`

Cargo.lock, crates/datasources/Cargo.toml, crates/datasources/src/bigquery/mod.rs
Also add `%error` to log when unable to send message over channel. Should help in debugging.
=> chore: Remove unnecessary lock from bigquery stream thread.

crates/sqlexec/src/context.rs, crates/sqlexec/src/planner/context_builder.rs, crates/sqlexec/src/planner/dispatch.rs, crates/sqlexec/src/planner/session_planner.rs, crates/sqlexec/src/session.rs
```
glaredb=> select now();
now()
-------------------------------
2023-08-07 20:35:57.042442+00
(1 row)
```
Fixes #1427
=> fix: `SELECT now()` returns current time.

py-glaredb/src/lib.rs, py-glaredb/src/session.rs, py-glaredb/src/util.rs, py-glaredb/tests/test_show.py
This is a fix for `show` not outputting anything in Google Colab. Stdout in colab gets routed through a few different layers, and just flushing wasn't doing anything. Using python's builtin `print` was just the easiest path for this, and since this isn't performance sensitive, I think it's reasonable to do.
Closes https://github.com/GlareDB/glaredb/issues/1470
=> fix: Use python print for `show` method

crates/rpcsrv/src/proxy.rs
The behavior will now properly translate the client request into a proxy request based on data returned from Cloud.
No tests for this... just trying to get it to work first.
=> fix: Properly translate client request to proxy request

crates/bench_runner/src/main.rs, crates/glaredb/src/bin/main.rs, crates/glaredb/src/local.rs, crates/glaredb/src/server.rs, crates/rpcsrv/src/handler.rs, crates/testing/src/slt/cli.rs
```shell
> glaredb server --ignore-auth --rpc-bind 0.0.0.0:6789
> glaredb local --ignore-auth -c http://0.0.0.0:6789
```
=> chore: Allow client init session when `--ignore-auth`.

crates/glaredb/src/local.rs, crates/pgsrv/src/handler.rs, crates/sqlexec/src/session.rs
Small tweaks:
```
> drop table a;
Table(s) dropped
```
=> feat: Slightly prettier execution result output

crates/glaredb/src/highlighter.rs, crates/glaredb/src/local.rs
this has been bothering me for a while, if you put in a multiline sql command, you were not able to use the history to re do your previous statement, as the history was stored line by line. 
now the history is stored per statement as it should
https://github.com/GlareDB/glaredb/assets/21327470/364e28ee-d9a8-41e7-b40b-f4fe0051e0a9
=> feat(cli): multiline history support

crates/protogen/proto/rpcsrv/service.proto, crates/protogen/src/lib.rs, crates/protogen/src/rpcsrv/types/service.rs, crates/rpcsrv/src/handler.rs, crates/rpcsrv/src/session.rs, crates/sqlexec/src/remote/client.rs, crates/sqlexec/src/remote/exec.rs, crates/sqlexec/src/remote/table.rs
```
> select * from abc;
┌───────┐
│ a     │
│ ──    │
│ Int32 │
╞═══════╡
│ 1     │
│ 2     │
│ 3     │
└───────┘
> insert into abc values (4), (5);
Write success
> select * from abc;
┌───────┐
│ a     │
│ ──    │
│ Int32 │
╞═══════╡
│ 1     │
│ 2     │
│ 3     │
│ 4     │
│ 5     │
└───────┘
```
**Logs:**
```
initializing remote session session_id=accc8ed7-d0e1-463a-834d-6f5ae2199668
dispatching table access session_id=accc8ed7-d0e1-463a-834d-6f5ae2199668 table_ref=abc
creating physical plan session_id=accc8ed7-d0e1-463a-834d-6f5ae2199668
executing physical plan session_id=accc8ed7-d0e1-463a-834d-6f5ae2199668 exec_id=e72dc636-faf9-4953-b3bb-0bd786a626e5
dispatching table access session_id=accc8ed7-d0e1-463a-834d-6f5ae2199668 table_ref=abc
creating physical plan …
```
=> feat: Support remote table scans and inserts

crates/datasources/src/common/url.rs, crates/glaredb/src/highlighter.rs, crates/protogen/proto/metastore/options.proto, crates/protogen/src/metastore/types/options.rs, crates/sqlbuiltins/src/functions/object_store.rs, crates/sqlexec/src/parser/options.rs, crates/sqlexec/src/planner/dispatch.rs, crates/sqlexec/src/planner/session_planner.rs, testdata/sqllogictests/functions/csv_scan.slt, testdata/sqllogictests_object_store/local/external_table.slt
Both for scan functions and external tables
```
> select count(*) from csv_scan(
::: 'testdata/sqllogictests_datasources_common/data/bikeshare_stations.csv.gz',
::: compression => 'gz'
::: );
┌─────────────────┐
│ COUNT(UInt8(1)) │
│ ──              │
│ Int64           │
╞═════════════════╡
│ 102             │
└─────────────────┘
> create external table abc from local (
::: location 'testdata/sqllogictests_datasources_common/data/bikeshare_stations.csv.gz',
::: file_type 'csv',
::: compression 'gz'
::: );
┌┐
└┘
> select count(*) from abc;
┌─────────────────┐
│ COUNT(UInt8(1)) │
│ ──              │
│ Int64           │
╞═════════════════╡
│ 102             │
└─────────────────┘
```
Fixes #1491
=> fix: Use named arguments for file compression

crates/protogen/src/sqlexec/logical_plan.rs, crates/sqlexec/src/extension_codec.rs, crates/sqlexec/src/planner/extension.rs, crates/sqlexec/src/planner/logical_plan.rs, crates/sqlexec/src/planner/logical_plan/set_variable.rs, crates/sqlexec/src/planner/logical_plan/show_variable.rs, crates/sqlexec/src/planner/session_planner.rs, crates/sqlexec/src/session.rs
closes #1567 
can set variables on remote via `SET <variable>` and locally via `SET LOCAL <variable>`. 
when running on a single instance, both ops behave the same.
=> rpc variable execs

Cargo.lock, crates/datafusion_ext/Cargo.toml, crates/datasources/src/postgres/mod.rs, crates/sqlbuiltins/src/functions/postgres.rs, crates/sqlbuiltins/src/functions/virtual_listing.rs, crates/sqlexec/src/planner/dispatch.rs, crates/sqlexec/src/planner/session_planner.rs
Small refactor on the postgres stuff which allow reconstructing a postgres table provider and/or the binary copy exec with serializable values.
Started this because the broadcast/exchange stuff will be a lot easier when working with physical plans, and so I want to try to get the physical plan serialization done quickly. Other data sources should be able to follow this pattern of if we have the client, use that, otherwise create one.
=> feat: Allow reconstructing postgres table provider and execs

crates/glaredb/src/local.rs, crates/sqlexec/src/remote/client.rs
=> feat: Display deployment name when connecting with local

Cargo.lock, crates/metastore/Cargo.toml, crates/metastore/src/database.rs, crates/metastore/src/errors.rs, crates/metastore/src/srv.rs, crates/protogen/proto/metastore/service.proto, crates/sqlexec/src/metastore/client.rs
Removes needing to "init" a catalog before fetching or mutating it. Since we create catalogs lazily, the only thing "init" was doing was loading it into memory. This change makes it so that that other two endpoints just do that automatically if the catalog isn't found.
These errors should no longer happen:
```
Missing database catalog: cbdfc895-3d01-4771-92b6-9ab1c43a3bb9
```
(because I deleted it)
=> chore: Remove init catalog endpoint for metastore

.github/workflows/ci.yaml, crates/sqlexec/src/planner/physical_plan/client_recv.rs, crates/sqlexec/src/planner/physical_plan/client_send.rs, crates/sqlexec/src/planner/physical_plan/remote_exec.rs, crates/sqlexec/src/planner/physical_plan/send_recv.rs, crates/sqlexec/src/remote/client.rs, crates/sqlexec/src/remote/local_side.rs, crates/sqlexec/src/remote/planner.rs, crates/testing/src/slt/cli.rs, testdata/sqllogictests/functions/parquet_scan.slt, testdata/sqllogictests/rpc.slt
- Current execs assume a single partition, so added a coalesce exec to ensure that is the case.
- Was sending the wrong schema in the recv exec causing projection issues.
- Added some SLTs that I was using for testing this.
- Add section in github workflow for running SLTs with rpc. We can enable more tests as we go along.
Closes #1597 
Closes #1602
=> fix: Fix projection/partition related bugs with remote planner

Cargo.lock, Cargo.toml, crates/sqlexec/src/context/local.rs, crates/sqlexec/src/metastore/catalog.rs
moves the catalog mutator into the session context. 
the mutator already had internal mutability, so no need to create a wrapper like i did with sessionvars. 
the patch to datafusion is still needed as mentioned in #1607
=> refactor: catalog mutator

crates/sqlexec/src/session.rs
the default `state.create_physical_plan` optimizes the lp before creating it. We should as well. It was causing some issues with `Explain`
=> fix: optimize lp before creating physical plan

CONTRIBUTING.md, crates/pgsrv/src/handler.rs, testdata/pgprototest/ddl.pt
Was incorrectly sending back row descriptions for all queries, including DDL. This is due to all logical/physical plans now having schemas.
Also adds a protocol test for this.
=> fix(pgsrv): Send row description only for 'Query' results

crates/logutil/src/lib.rs
```
2023-08-27T22:50:49.908031Z DEBUG tower::buffer::worker: service.ready: true, processing request
at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-0.4.13/src/buffer/worker.rs:197 on server-thread-1 ThreadId(3)
in sqlexec::metastore::client::fetch_interval with db_id: 00000000-0000-0000-0000-000000000000
2023-08-27T22:50:49.911039Z DEBUG sqlexec::engine: new session opened, session_count: 1
at crates/sqlexec/src/engine.rs:161 on server-thread-7 ThreadId(9)
in glaredb::server::glaredb_connection with conn_id: f33becfd-4d60-4c65-a35d-2c4bc1301757
2023-08-27T22:50:49.964877Z DEBUG metastore::srv: fetch catalog, req: FetchCatalogRequest { db_id: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }
at crates/metastore/src/srv.rs:76 on server-thread-6 ThreadId(8) …
```
=> chore: Enable pretty logging

.github/workflows/ci.yaml, crates/sqlexec/src/extension_codec.rs, testdata/sqllogictests/rpc.slt
Closes #1661 
Was using the schema of the _output_ of the create table execs, and the schema for the table itself.
```
> \open http://localhost:6542
Connected to Cloud deployment: unknown
> create table hello (a int, b int, c int);
Table created
> insert into hello select 1, 2, 3;
Inserted 1 row
> select * from hello;
┌───────┬───────┬───────┐
│ a     │ b     │ c     │
│ ──    │ ──    │ ──    │
│ Int32 │ Int32 │ Int32 │
╞═══════╪═══════╪═══════╡
│ 1     │ 2     │ 3     │
└───────┴───────┴───────┘
```
=> fix(rpc): Use correct schema when serialize create table execs

Cargo.lock, Cargo.toml, crates/datafusion_ext/src/local_hint.rs, crates/datafusion_ext/src/planner/expr/identifier.rs, crates/datafusion_ext/src/planner/expr/mod.rs, crates/datafusion_ext/src/planner/set_expr.rs, crates/datafusion_ext/src/planner/utils.rs, crates/datasources/src/common/sink/csv.rs, crates/datasources/src/common/sink/json.rs, crates/datasources/src/common/sink/parquet.rs, crates/datasources/src/native/access.rs, crates/datasources/src/object_store/mod.rs, crates/pgrepr/src/writer.rs, crates/sqlbuiltins/src/functions/object_store.rs, crates/sqlexec/src/dispatch/external.rs, crates/sqlexec/src/parser/options.rs, crates/sqlexec/src/planner/physical_plan/copy_to.rs, crates/sqlexec/src/planner/physical_plan/create_temp_table.rs, crates/sqlexec/src/planner/physical_plan/insert.rs, crates/sqlexec/src/planner/session_planner.rs, crates/sqlexec/src/remote/local_side.rs, crates/sqlexec/src/remote/table.rs
Upstream pr for delta-rs: https://github.com/delta-io/delta-rs/pull/1606
=> chore: Update delta-rs to fork and datafusion to 30

crates/protogen/src/sqlexec/physical_plan.rs, crates/sqlexec/src/extension_codec.rs, crates/sqlexec/src/planner/physical_plan/mod.rs, crates/sqlexec/src/planner/physical_plan/values.rs, testdata/sqllogictests/rpc.slt
```
Connected to Cloud deployment: unknown
GlareDB (v0.4.0)
>
> values (1), (2), (3);
┌─────────┐
│ column1 │
│ ──      │
│ Int64   │
╞═════════╡
│ 1       │
│ 2       │
│ 3       │
└─────────┘
>
> create table abc (a int, b text);
Table created
>
> insert into abc
::: values (1, 'something'), (2, 'another thing');
Inserted 2 rows
>
> select * from abc;
┌───────┬───────────────┐
│ a     │ b             │
│ ──    │ ──            │
│ Int32 │ Utf8          │
╞═══════╪═══════════════╡
│ 1     │ something     │
│ 2     │ another thing │
└───────┴───────────────┘
```
Fixes: #1665
=> fix: Serialize `ValuesExec` for RPC.

crates/sqlexec/src/planner/context_builder.rs, testdata/sqllogictests/rpc.slt
This is not optimal, but it gets views working.
```
GlareDB (v0.4.0)
> \open http://localhost:6542
Connected to Cloud deployment: unknown
> create view hello as select 1;
View created
> select * from hello;
┌──────────┐
│ Int64(1) │
│ ──       │
│ Int64    │
╞══════════╡
│ 1        │
└──────────┘
```
=> fix: Dispatch views locally

crates/sqlexec/src/remote/planner.rs, crates/sqlexec/src/remote/rewriter.rs, testdata/sqllogictests/functions/parquet_scan.slt
We rewrite any `CopyTo` plan (in the remote planner) that has a copy to
local destination and replace it with the source query. The rewriter
collects the format and destination of the copy to plan and we wrap the
`SendRecvJoinExec` with a `CopyToExec` for local.
Fixes #1600
=> feat: Remote to local copy to

crates/testing/src/slt/test.rs
=> fix: Return only "NULL" when value is null in RPC SLT

crates/datafusion_ext/src/functions.rs, crates/datafusion_ext/src/planner/mod.rs, crates/datafusion_ext/src/planner/relation/mod.rs, crates/metastore/src/database.rs, crates/protogen/proto/metastore/catalog.proto, crates/protogen/proto/rpcsrv/service.proto, crates/protogen/src/metastore/types/catalog.rs, crates/protogen/src/rpcsrv/types/func_param_value.rs, crates/protogen/src/rpcsrv/types/mod.rs, crates/protogen/src/rpcsrv/types/service.rs, crates/rpcsrv/src/errors.rs, crates/rpcsrv/src/handler.rs, crates/rpcsrv/src/session.rs, crates/sqlbuiltins/src/functions/bigquery.rs, crates/sqlbuiltins/src/functions/delta.rs, crates/sqlbuiltins/src/functions/generate_series.rs, crates/sqlbuiltins/src/functions/iceberg.rs, crates/sqlbuiltins/src/functions/mongo.rs, crates/sqlbuiltins/src/functions/mysql.rs, crates/sqlbuiltins/src/functions/object_store.rs, crates/sqlbuiltins/src/functions/postgres.rs, crates/sqlbuiltins/src/functions/snowflake.rs, crates/sqlbuiltins/src/functions/virtual_listing.rs, crates/sqlexec/src/context/remote.rs, crates/sqlexec/src/dispatch/external.rs, crates/sqlexec/src/dispatch/mod.rs, crates/sqlexec/src/errors.rs, crates/sqlexec/src/planner/context_builder.rs, crates/sqlexec/src/remote/client.rs
So this moves all of the tablefunc exec logic into the dispatcher (similar to how we are doing with tables). 
The functions are a bit more dynamic than the tables and as such, we sometimes need to determine the execution preference at runtime. 
**Ideally I wanted to do this during physical planning**. 
However, the logical planner needs the schema, so we needed to move the logic further upstream and determine if the function should run remote or locally before we get to the LogicalPlan. Otherwise we end up performing schema scans locally, and table scans remotely which causes the state to get out of sync.
--- 
Implicitly we know that: 
- some functions will always to run remotely when possible (s3, postgres, bigquery,...)
- some always locally (local filesystem)
- some determined at …
=> feat: remote execution of table funcs via dispatcher

crates/testing/src/slt/cli.rs
Closes https://github.com/GlareDB/glaredb/issues/1587
(And should make main pass)
=> chore: Bump stack size for SLT tests

.github/workflows/ci.yaml, crates/protogen/src/sqlexec/physical_plan.rs, crates/sqlexec/src/extension_codec.rs
Adds serialization for InterleaveExec which allows unions to work.
Also enabled more SLT tests now that more of the catalog is working.
Closes https://github.com/GlareDB/glaredb/issues/1678
=> feat: Serialize InterleaveExec

crates/sqlexec/src/planner/physical_plan/remote_exec.rs
Before:
```
> create table t1 (a int);
Error: Execution error: failed to pull next batch from stream: status: Unknown, message: "Execution error: failed to create table in catalog: Failed Metastore request: Duplicate name: t1", details: [], metadata: MetadataMap { headers: {} }
```
After:
```
> create table t1 (a int);
Error: Execution error: Remote node error: Execution error: failed to create table in catalog: Failed Metastore request: Duplicate name: t1
```
Closes https://github.com/GlareDB/glaredb/issues/1713
=> chore: Tighten up execution response error

crates/datafusion_ext/src/runtime/group_pull_up.rs
groups related children in unions 
for example: takes a query 
```sql
select * from local where c = 1
union (select * from local where c = 2)
union (select * from remote where c = 3)
```
and rewrites the initial plan of 
```mermaid
graph TD
UnionExec --> FilterExec1 & FilterExec2 & FilterExec3
FilterExec1 --> RemoteExec1
FilterExec2 --> LocalExec1
FilterExec3 --> LocalExec2
subgraph Remote
RemoteExec1 --> EmptyExec1["EmptyExec (test_schema)"]
end
subgraph Local1[Local]
LocalExec1 --> EmptyExec2["EmptyExec (test_schema)"]
end
subgraph Local2[Local]
LocalExec2 --> EmptyExec3["EmptyExec (test_schema)"]
end
```
to 
```mermaid
graph TD
UnionExec --> RemoteExec & LocalExec
subgraph Local
LocalExec -->
UnionExecLocal[UnionExec] --> LocalExec1 & LocalExec2
LocalExec1 --> EmptyExec2["EmptyExec …
```
=> feat: add further optimizations for hybrid unions

Cargo.lock, crates/glaredb/src/bin/main.rs, crates/glaredb/src/commands.rs, crates/glaredb/src/server.rs, crates/logutil/Cargo.toml, crates/logutil/src/lib.rs, crates/metastore/src/local.rs, crates/metastore/src/srv.rs, crates/protogen/src/rpcsrv/types/service.rs, crates/rpcsrv/src/handler.rs, crates/testing/src/slt/cli.rs, testdata/sqllogictests/joins/inner_join/using_join.slt
depends on #1717
closes #1662
- adds `--log-mode=[compact,full,json]` instead of `--json-logging`
- moves a few info logs to `debug` as they didn't seem to be super useful for non debugging purposes. 
now when i start the server, i can get a more compact output in my terminal without a wall of text
The `full` format is the default & behaves the same as it currently does.
=> feat: more logging options

crates/datasources/src/common/mod.rs, crates/sqlbuiltins/src/functions/object_store.rs, crates/sqlexec/src/dispatch/external.rs
This is a temporary fix where a CSV file might have an identifier such as `NA` signifying `NULL` in a non-string column.
Context: #1707
=> fix: Increase schema infer max rec size to 20480.

.github/workflows/python-release.yaml
By using the manylinux container.
Needed for compatibility in fabric. Currently their version of python supports glibc up to version 2.27. We currently build with glibc 2.31. Eventually, I want to never have to deal with glibc again.
Manually tested:
=> fix: Lower glibc version for python releases

crates/pgsrv/src/messages.rs, testdata/csv/empty_col.csv, testdata/sqllogictests/csv.slt
This specifically fixes the case where we query a csv file with an unnamed column. Previously we were explicity checking the column name was empty, and now we don't.
This has the consequence of allowing a user to select the empty column with `select "" from ...`, but I guess that's expected.
Closes https://github.com/GlareDB/glaredb/issues/1750
=> fix: Allow returning query response through pgsrv with empty column

crates/protogen/src/sqlexec/physical_plan.rs, crates/sqlexec/src/extension_codec.rs, testdata/sqllogictests/rpc.slt
=> fix: serialize AnalyzeExec

crates/glaredb/src/highlighter.rs
Closes: https://github.com/GlareDB/glaredb/issues/1759
=> fix: syntax highilight for semi-colon for light and dark backgrounds

crates/glaredb/src/args/local.rs
We're only at a partial impl right now, and I don't want to break
current (working) interfaces. We will eventually make it "ON" by
default once it's fully implemented.
=> chore: set default for `--disable-tls`

crates/testing/src/slt/test.rs, testdata/sqllogictests/explain.slt
The explain test failed due to not matching a new line character at the
end. It's much simpler to omit any leading or trailing whitespaces from
a row given the nature of SLTs.
Fixes #1793
=> fix: Trim whitespaces when checking SLT output

crates/sqlexec/src/planner/errors.rs, crates/sqlexec/src/planner/session_planner.rs, testdata/sqllogictests_object_store/gcs/delta.slt, testdata/sqllogictests_object_store/local/iceberg.slt, testdata/sqllogictests_object_store/s3/delta.slt
Align handling of Delta and Iceberg external tables with other variants by eagerly validating the object store connectivity.
Closes #1817
=> feat: Implement Delta/Iceberg external table validation during initial setup

crates/glaredb/src/args/local.rs, py-glaredb/src/lib.rs
This alters the pyFunction `connect` to have two additional optional arguments `disable_tls` and `cloud_addr`. These arguments match those that are defined in `LocalClientOpts`.
```
glaredb.connect([data_dir_or_cloud_url], [spill_path])
```
`data_dir_or_cloud_url` is positional, and all other args are keyword with defaults and variable in order
```
glaredb.connect([data_dir_or_cloud_url],
[spill_path],
[disable_tls],
[cloud_addr]
)
```
```py
import glaredb
conn = glaredb.connect()
conn.sql("SELECT 'hello local';").show()
│ Utf8("hello local") │
│ ──                  │
│ Utf8                │
╞═════════════════════╡
│ hello local         │
```
```py
import glaredb
cloud_url = "<user>:<pass>@<org>.remote.qa.glaredb.com:6443/<db_name>"
conn = …
```
=> chore(py-glaredb): keyword args for connect

Cargo.lock, Cargo.toml, crates/datasources/src/native/access.rs, crates/datasources/src/native/insert.rs
a few things were renamed in delta. this also uses the commit instead of branch to make sure we are locked on a specific version instead of just `main`
=> chore: update delta version

.github/workflows/ci.yaml, crates/sqlexec/src/planner/physical_plan/remote_scan.rs
Since we're executing and collecting the complete stream in `RemoteScanExec`, we need to coalesce all the partitions before executing else we end up running only the first partition.
Fixes #1812
=> fix: Coalesce partitions in `RemoteScanExec`

.github/workflows/ci.yaml, crates/testing/tests/sqllogictests/hooks.rs
1. Sleep a bit more after certain about the server has started.
2. Run each SSH tunnel job one-by-one.
Fixes #1054 (hopefully)
=> chore: Fix flaky SSH tunnel tests

py-glaredb/Cargo.toml
Not used and it was causing warnings
Closes https://github.com/GlareDB/glaredb/issues/1833
=> chore: Remove release profile settings from py-glaredb

crates/datafusion_ext/src/lib.rs, crates/datafusion_ext/src/metrics.rs, crates/datafusion_ext/src/runtime/runtime_group.rs, crates/datasources/src/bigquery/mod.rs, crates/datasources/src/mongodb/exec.rs, crates/datasources/src/mysql/mod.rs, crates/datasources/src/native/access.rs, crates/datasources/src/object_store/http.rs, crates/datasources/src/object_store/mod.rs, crates/datasources/src/postgres/mod.rs, crates/datasources/src/snowflake/mod.rs, crates/protogen/src/sqlexec/physical_plan.rs, crates/sqlexec/src/dispatch/external.rs, crates/sqlexec/src/extension_codec.rs
Adds additional metrics tracking for data sources:
```
> CREATE EXTERNAL DATABASE my_pg
::: FROM postgres OPTIONS (
:::   host = 'pg.demo.glaredb.com',
:::   port = '5432',
:::   user = 'demo',
:::   password = 'demo',
:::   database = 'postgres',
::: );
Database created
> explain analyze select * from my_pg.public.customer;
┌───────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ plan_type         │ plan                                                                                                                                             │
│ ──                │ ── …
```
=> feat: Track more data source metrics during execution

crates/rpcsrv/src/handler.rs, crates/sqlexec/src/context/mod.rs, crates/sqlexec/src/context/remote.rs, crates/sqlexec/src/engine.rs
Related to distributed execution.
Goal: Try to make the remote session as stateless as possible to allow for it to execute any plan for a specific database.
There's still some need for `SessionVars` when creating the datafusion runtime/context, but I just used the default for now. It's likely that we'll just be provided a well-typed struct for session configuration soonish.
=> chore: Remove temp catalog, session vars (mostly) from remote session

crates/arrow_util/src/pretty.rs
closes #1769 
before:
```
> select current_schemas();
┌────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ current_schemas                                                                                    │
│ ──                                                                                                 │
│ List(Field { name: "item", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, m… │
╞════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ [public]                                                                                           │
└────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
after:
```
> select …
```
=> chore: better list dtype formatting

.github/workflows/ci.yaml, crates/bench_runner/src/main.rs, crates/glaredb/src/args/server.rs, crates/glaredb/src/commands.rs, crates/glaredb/src/server.rs, crates/sqlexec/src/engine.rs, crates/testing/src/slt/cli.rs, scripts/create-test-minio-store.sh
The simplest way to go about this seemed to be:
- extending the server command to also accept the storage config options (as the local command)
- add a script to spin up a MinIO server and create a bucket in it
- Add a relevant invocation to the `ci.yaml` file to trigger all that
=> feat: Extend SLTs to excercise remote data storage functionality

.github/workflows/release.yaml
Build every Monday instead of every day. We're not currently making use of these "nightly" builds, and so there's some wasted work going. Having _some_ automated builds is nice though to catch possible breakages prior to actually trying to release.
cc @greyscaled
=> chore: Reduce number of release builds

crates/datasources/src/common/util.rs, crates/datasources/src/postgres/mod.rs, crates/datasources/src/postgres/query_exec.rs, crates/protogen/src/metastore/types/catalog.rs, crates/protogen/src/sqlexec/physical_plan.rs, crates/sqlexec/src/extension_codec.rs, crates/sqlexec/src/planner/logical_plan/insert.rs, crates/sqlexec/src/planner/physical_plan/insert.rs, crates/sqlexec/src/planner/physical_plan/remote_scan.rs, crates/sqlexec/src/planner/session_planner.rs, crates/sqlexec/src/remote/planner.rs, crates/sqlexec/src/remote/rewriter.rs, crates/sqlexec/src/remote/table.rs
Lays down the framework for inserting into external sources.
Supporting inserts *should* be as simple as implementing the `insert_into` method for table providers.
This PR implements `insert_into` for Postgres datasource.
Fixes: #1883
Epic: #1143
=> feat: Support `INSERT INTO` for external sources.

Cargo.lock, crates/datafusion_ext/src/vars.rs, crates/datafusion_ext/src/vars/constants.rs, crates/datafusion_ext/src/vars/inner.rs, crates/datafusion_ext/src/vars/value.rs, crates/glaredb/src/local.rs, crates/pgsrv/src/handler.rs, crates/sqlexec/Cargo.toml, crates/sqlexec/src/parser.rs, crates/sqlexec/src/session.rs, testdata/sqllogictests/prql.slt
allows users to use the experimental `prql` language instead of sql
closes #1772 
See https://prql-lang.org/ for more info.
To use, simply set the dialect
```sql
set dialect = 'prql';
```
then you can use prql syntax
```elm
from my_table 
filter some_column == "hello world"
take 1
```
To switch back to sql, just set the dialct to `sql`
```sql
set dialect = 'sql';
```
custom table functions & expressions are not yet supported, This gives us relatively limited prql functionality & should be marked as experimental.
=> feat: experimental prql support

crates/glaredb/src/args/local.rs, crates/glaredb/src/commands.rs
**`test.sql`**:
```sql
-- Create a new table
CREATE TABLE test (
col1 INTEGER,
col2 TEXT
);
-- Insert some values into the table
INSERT INTO test VALUES
(1, 'Hello'),
(2, 'Bye');
-- Run a very complicated query
SELECT * FROM test;
```
Shell:
```shell
> glaredb test.sql # or glaredb local test.sql
Table created
Inserted 2 rows
┌───────┬───────┐
│  col1 │ col2  │
│    ── │ ──    │
│ Int32 │ Utf8  │
╞═══════╪═══════╡
│     1 │ Hello │
│     2 │ Bye   │
└───────┴───────┘
```
=> feat: Enable passing SQL script as an argument

.github/workflows/ci.yaml, crates/pgrepr/src/writer.rs, crates/sqlexec/src/context/local.rs, crates/sqlexec/src/session.rs, crates/testing/tests/sqllogictests/main.rs, crates/testing/tests/sqllogictests/tests.rs
=> feat: Enable binary encoding when requested by the client

crates/datasources/src/common/url.rs, crates/datasources/src/object_store/local.rs, crates/sqlbuiltins/src/functions/object_store.rs, testdata/sqllogictests/functions/parquet_scan.slt
closes #1897
closes https://github.com/GlareDB/glaredb/issues/1936
The error messages should properly bubble up now. 
Additionally, we now canonicalize the relative paths during `DatasourceUrl::try_new`. This ensures that the path is absolute, and that it is a valid file/directory.
=> fix: add better error messages for parsing datasource urls

.github/workflows/benchmarks.yaml, .github/workflows/ci.yaml, .github/workflows/python-release.yaml, rust-toolchain.toml
closes #1946
adding a [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) will prevent any inconsistencies during development as noticed in #1946.
=> add rust-toolchain.toml

py-glaredb/glaredb/__init__.py
I'm not sure what this is actually for, but it seems like it's needed for me to run stuff locally.
We previously had this file, but it was deleted in https://github.com/GlareDB/glaredb/pull/1909 which I don't believe was intentional.
Fixes https://github.com/GlareDB/glaredb/issues/2006
=> chore: Add back __init__.py file

Cargo.lock, crates/arrow_util/Cargo.toml, crates/arrow_util/src/pretty.rs, crates/glaredb/Cargo.toml, crates/glaredb/src/local.rs, js-glaredb/src/execution_result.rs, py-glaredb/src/execution_result.rs
And instead alway require that it's passed in. Removes some magic and makes things a bit more reproducible.
Fixes https://github.com/GlareDB/glaredb/issues/2005 (terminal width was getting reported as zero inside eshell)
=> fix: Remove terminal width detection from pretty table

crates/glaredb/src/rpc_proxy.rs
This is progress towards #1828. After testing, the next step would be to turn the `disable_tls` in `LocalClientOpts` and `connect` annotation in py-glaredb
=> !experiment(rpc_proxy): client_auth_optional

crates/testing/src/slt/test.rs, justfile
closes #2012
We weren't using the prql aware parser, but instead the `parse_sql` function
=> fix: prql slt runner

bindings/nodejs/src/connect.rs, bindings/python/src/connect.rs, crates/glaredb/src/args/local.rs, crates/glaredb/src/rpc_proxy.rs, crates/sqlexec/src/remote/client.rs
=> feat(rpc)!: enable TLS

bindings/nodejs/index.d.ts, bindings/nodejs/src/connect.rs, bindings/nodejs/src/connection.rs, bindings/nodejs/src/logical_plan.rs
just adds `catch_unwind` to all public methods to prevent panics.
=> chore(bindings-node): add catch_unwind

crates/sqlexec/src/remote/client.rs
Examples:
1. Auth errors (connection string, `--cloud-addr` mismatch etc)
```shell
$ cargo run --bin glaredb -- --cloud-url=<URL> --cloud-addr=https://console.glaredb.com
GlareDB (v0.6.1)
Error: authentication failed
```
2. Version out of date (0.7.0):
```shell
$ cargo run --bin glaredb -- --cloud-url=<URL> --cloud-addr=https://qa.glaredb.com
GlareDB (v0.6.1)
Error: version unsupported: update to glaredb v0.7.0 or later: hint: curl https://glaredb.com/install.sh | sh
```
=> feat(sqlexec rpc): client auth error messages

bindings/nodejs/example.js, bindings/nodejs/examples/commonjs.js, bindings/nodejs/examples/esm.js
removes the `example.js` and instead adds  `examples/commonjs` and `examples/esm`. 
The commonjs one can be run with node without any transpilation or special configuration
```sh
node examples/commonjs.js
```
The esm one requires module support which is not provided with node out of the box, but is easily run via bun
```sh
bun examples/esm.js
```
closes #2063
=> chore(bindings-node): update examples

Cargo.toml
Closes https://github.com/GlareDB/glaredb/issues/2119
It's no longer a feature.
=> chore: Remove 'parquet' feature from deltalake dep

Cargo.lock, crates/glaredb/Cargo.toml, crates/glaredb/src/args/local.rs, crates/glaredb/src/bin/main.rs, crates/glaredb/src/commands.rs, crates/glaredb/src/local.rs, crates/glaredb/tests/logging_test.rs, crates/glaredb/tests/output_mode_test.rs, crates/glaredb/tests/setup.rs, crates/glaredb/tests/version_test.rs
closes https://github.com/GlareDB/glaredb/issues/2136.
Also adds some simple integration tests to the cli. These aren't all related to #2136, and i can pull them into a separate PR if necessary. I was originally working on adding tests when I uncovered #2136.
=> fix: stdin piping 

crates/sqlexec/src/planner/session_planner.rs, testdata/csv/case_sensitive_columns.csv, testdata/sqllogictests/create_table.slt
closes #2034 
Turns out there was some implicit casting with `Into<Column>` + `DfField::name` that was casting it to lowercase. Using `DfField::unqualified_column` instead preserves the original field name.
=> fix: case sensitivity in create table

.github/workflows/ci.yaml, .github/workflows/nodejs-release.yml
See https://github.com/actions/setup-node/issues/899
When defining `packageManager` in package.json, github runners will now error about using the wrong yarn version. This change seems like it'll be a temp fix until either the setup-node action or github runner gets update (to what exactly, I'm not sure, but we should follow the issue).
=> chore: Enable corepack before setting up node

.github/workflows/ci.yaml, crates/protogen/src/metastore/types/catalog.rs, crates/sqlbuiltins/src/builtins.rs, crates/sqlexec/src/dispatch/system.rs, justfile, testdata/sqllogictests/allowed_operations.slt
Tables:
```
> CREATE EXTERNAL TABLE debug_table
:::     FROM debug (
:::         table_type 'never_ending'
:::     );
Table created
> select * from glare_catalog.tables;
┌────────┬──────────────┬────────────┬──────────────┬───┬─────────┬──────────┬────────────┬─────────────┐
│    oid │ database_oid │ schema_oid │ schema_name  │ … │ builtin │ external │ datasource │ access_mode │
│     ── │           ── │         ── │ ──           │   │ ──      │ ──       │ ──         │ ──          │
│ UInt32 │       UInt32 │     UInt32 │ Utf8         │   │ Boolean │ Boolean  │ Utf8       │ Utf8        │
╞════════╪══════════════╪════════════╪══════════════╪═══╪═════════╪══════════╪════════════╪═════════════╡
│  16488 │        16384 │      16385 │ glare_catal… │ … │ true    │ false    │ internal   │ …
```
=> feat: Add 'access_mode' column for databases and tables

bindings/nodejs/src/connection.rs, bindings/nodejs/src/logical_plan.rs, bindings/python/src/connection.rs, bindings/python/src/logical_plan.rs, crates/protogen/proto/rpcsrv/service.proto, crates/protogen/src/rpcsrv/types/service.rs, crates/rpcsrv/src/handler.rs, crates/sqlexec/src/lib.rs, crates/sqlexec/src/planner/logical_plan/mod.rs, crates/sqlexec/src/planner/physical_plan/remote_exec.rs, crates/sqlexec/src/remote/client.rs, crates/sqlexec/src/remote/planner.rs, crates/sqlexec/src/session.rs
```json
{
"database_id": "00000000-0000-0000-0000-000000000000",
"connection_id": "00000000-0000-0000-0000-000000000000",
"query_text": "SELECT * FROM my_pg.public.lineitem WHERE l_shipdate <= DATE '1998-12-01' - INTERVAL '90' LIMIT 5",
"telemetry_tag": "unknown",
"execution_status": "success",
"error_message": null,
"elapsed_compute_ns": 11627950,
"output_rows": 5,
"bytes_read": 15466360,
"bytes_written": 0
}
```
=> chore: Send query text when executing query over RPC

crates/metastore/src/database.rs, crates/sqlbuiltins/src/builtins.rs, crates/sqlbuiltins/src/functions/aggregates.rs, crates/sqlbuiltins/src/functions/mod.rs, crates/sqlbuiltins/src/functions/scalars.rs, crates/sqlbuiltins/src/functions/table/bigquery.rs, crates/sqlbuiltins/src/functions/table/delta.rs, crates/sqlbuiltins/src/functions/table/excel.rs, crates/sqlbuiltins/src/functions/table/generate_series.rs, crates/sqlbuiltins/src/functions/table/iceberg.rs, crates/sqlbuiltins/src/functions/table/iceberg/data_files.rs, crates/sqlbuiltins/src/functions/table/iceberg/scan.rs, crates/sqlbuiltins/src/functions/table/iceberg/snapshots.rs, crates/sqlbuiltins/src/functions/table/lance.rs, crates/sqlbuiltins/src/functions/table/mod.rs, crates/sqlbuiltins/src/functions/table/mongo.rs, crates/sqlbuiltins/src/functions/table/mysql.rs, crates/sqlbuiltins/src/functions/table/object_store.rs, crates/sqlbuiltins/src/functions/table/postgres.rs, crates/sqlbuiltins/src/functions/table/snowflake.rs, crates/sqlbuiltins/src/functions/table/virtual_listing.rs
Moves it close to where it's implemented. The 'builtins' file is already a bit big.
=> chore: Move table func trait

crates/datafusion_ext/src/transform.rs, crates/sqlexec/src/planner/physical_plan/remote_scan.rs, crates/sqlexec/src/remote/planner.rs
Push down "remote" exec as far down as possible and replace any "local"
execs that are found (children to the remote). Finally, pack the
remote exec in a [`SendRecvJoinExec`] so the plan transformation looks
something like:
```txt
+-----------+
| A (Local) |
+-----+-----+
|
v
+-----------------+
+-------+ B (Unspecified) +-------+
|       +--------+--------+       |
v                |                v
+------------+         |          +-----------+
| C (Remote) |         |          | F (Local) |
+-----+------+         v          +-----------+
|          +------------+
v          | E (Remote) |
+-----------+    +------------+
| D (Local) |
+-----------+
```
```txt
+-----------+
| A (Local) |
+-----+-----+
|
v
+-----------------+
+-------------+ B (Unspecified) +-------+
| …
```
=> fix: Hybrid planning when the root plan has local preference

crates/sqlexec/src/planner/errors.rs, crates/sqlexec/src/planner/session_planner.rs
Simple update to error message.
=> chore: Fix error message for invalid copy-to

crates/bench_runner/src/main.rs, crates/glaredb/src/commands.rs, crates/glaredb/src/server.rs, crates/pgsrv/src/auth.rs, crates/testing/src/slt/cli.rs
closes out the `// TODO: Pull out args into a struct.`
=> chore: small cleanup to `ComputeServer`

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, crates/datasources/Cargo.toml, crates/glaredb/Cargo.toml, crates/glaredb/src/bin/main.rs, crates/glaredb/tests/log_file_test.rs, crates/glaredb/tests/setup.rs, justfile
Turns out we weren't actually running any of the tests in `glaredb/tests`. This fixes some issues that were identified when running those tests. 
Additionally updates the unit test command to properly run all unit tests.
=> fix: some broken tests

crates/arrow_util/src/pretty.rs
Fixes the issue #1807 
Tried to truncate long floats to have 5 digits after decimal point.
Added Unit Test for a batch of floats. 
@universalmind303 I abandoned the previous logic of having a config parameter to control number of digits after decimal point, instead hardcoded it. Please suggest any corrections.
Thanks in advance.
=> fix: truncate long floats in cli formatting for display

crates/glaredb/src/pg_proxy.rs
- Lowers log level for unexpected eof errors (client disconnects).
- Raises log level for all other errors
Closes https://github.com/GlareDB/glaredb/issues/2255
=> chore: Detect client disconnect in pg proxy

crates/datasources/src/postgres/mod.rs
Fixes issue : #2025 
Filters out unknown type - oids and returns them in error log.
@scsmithr  Please correct me if needed.
Thanks.
=> fix: filter unknown oids for Postgres types

crates/glaredb/src/bin/main.rs, crates/glaredb/src/server.rs, crates/glaredb/tests/server_args_test.rs, crates/logutil/src/lib.rs
Easier to read when running Cloud+GlareDB in the same terminal.
=> chore: Default to compact logs

.gitignore, Cargo.lock, crates/glaredb/Cargo.toml, crates/glaredb/src/args/local.rs, crates/glaredb/src/commands.rs, crates/sqlexec/src/distexec/scheduler.rs, justfile
Until I figure out the best solution (which hopefully is close).
Pushing just to benchmark and test stuff successfully.
To run the tokio console debugger:
1. Download the CLI:
```
cargo --locked tokio-console
```
2. Build/Run local with new just commands (along with `--debug-tokio` flag):
```
just run-debug-tokio local --debug-tokio
```
**NOTE:** This builds in a new `target` directory: `unstable-tokio-target` so as to not mess up with existing target directory (which can cause issues with LSP etc.).
=> fix: Hacky fix for running the experimental scheduler when spawning task

crates/datafusion_ext/src/errors.rs, crates/metastore/src/database.rs, crates/protogen/proto/metastore/catalog.proto, crates/protogen/src/metastore/types/catalog.rs, crates/sqlbuiltins/src/functions/mod.rs, crates/sqlbuiltins/src/functions/table/bigquery.rs, crates/sqlbuiltins/src/functions/table/bson.rs, crates/sqlbuiltins/src/functions/table/delta.rs, crates/sqlbuiltins/src/functions/table/excel.rs, crates/sqlbuiltins/src/functions/table/generate_series.rs, crates/sqlbuiltins/src/functions/table/iceberg/data_files.rs, crates/sqlbuiltins/src/functions/table/iceberg/scan.rs, crates/sqlbuiltins/src/functions/table/iceberg/snapshots.rs, crates/sqlbuiltins/src/functions/table/lance.rs, crates/sqlbuiltins/src/functions/table/mod.rs, crates/sqlbuiltins/src/functions/table/mongo.rs, crates/sqlbuiltins/src/functions/table/mysql.rs, crates/sqlbuiltins/src/functions/table/object_store.rs, crates/sqlbuiltins/src/functions/table/postgres.rs, crates/sqlbuiltins/src/functions/table/snowflake.rs, crates/sqlbuiltins/src/functions/table/system/cache_external_tables.rs, crates/sqlbuiltins/src/functions/table/virtual_listing.rs, crates/sqlexec/src/planner/context_builder.rs
We should only have 1 source of truth for runtime preference for the functions. Here, `runtime_preference` method is removed so the runtime is always calculated from `detect_runtime`.
Fixes #2165
=> chore: Remote `fn runtime_preference()` from `TableFunc` trait.

.clang-format, crates/protogen/proto/common/arrow.proto, crates/protogen/proto/metastore/catalog.proto, crates/protogen/proto/metastore/options.proto, crates/protogen/proto/metastore/service.proto, crates/protogen/proto/rpcsrv/common.proto, crates/protogen/proto/rpcsrv/service.proto
Adds a `.clang-format` file for configuring `clang-format` (I use it for auto-formatting protobufs).
My motivation for adding this in is by default clang-format will collapse a protobuf message with a single field and no comments into a single line.
For example, it will format this:
```protobuf
message Schema {
repeated Field columns = 1;
}
```
Into this:
```protobuf
message Schema { repeated Field columns = 1; }
```
I don't like that way of formatting, and the only reason we had it in the code base was because I was using a unconfigured clang-format.
Unfortunately I was not able to find a specific option for this (there's a ton, so I might've just missed it:
https://clang.llvm.org/docs/ClangFormatStyleOptions.html), so instead I just enabled the Google style. This seems to do mostly what …
=> chore: Add .clang-format

Cargo.lock, crates/glaredb/Cargo.toml, crates/glaredb/src/highlighter.rs, crates/glaredb/src/local.rs, crates/glaredb/tests/iss_2309.rs, crates/sqlbuiltins/src/functions/mod.rs, crates/sqlbuiltins/src/functions/table/mod.rs, testdata/sqllogictests/special_characters.slt
a number of improvements to the cli highlighter. 
- better support for types
- more support for various symbols `&|+-/%` 
- function highlighting!
=> feat: cli highlighting improvements.

.github/workflows/ci.yaml, Cargo.lock, crates/datasources/Cargo.toml, crates/datasources/src/clickhouse/errors.rs, crates/datasources/src/clickhouse/mod.rs, crates/datasources/src/clickhouse/stream.rs, crates/datasources/src/lib.rs, crates/datasources/src/object_store/mod.rs, crates/protogen/proto/metastore/catalog.proto, crates/protogen/proto/metastore/options.proto, crates/protogen/src/metastore/types/options.rs, crates/sqlbuiltins/src/functions/table/clickhouse.rs, crates/sqlbuiltins/src/functions/table/mod.rs, crates/sqlbuiltins/src/functions/table/postgres.rs, crates/sqlbuiltins/src/functions/table/virtual_listing.rs, crates/sqlexec/src/dispatch/external.rs, crates/sqlexec/src/dispatch/mod.rs, crates/sqlexec/src/planner/errors.rs, crates/sqlexec/src/planner/session_planner.rs, scripts/ci-install-clickhouse.sh, scripts/create-test-clickhouse-db.sh, scripts/create-test-minio-store.sh, testdata/sqllogictests_clickhouse/basic.slt, testdata/sqllogictests_clickhouse/data/setup-clickhouse.sql, testdata/sqllogictests_clickhouse/external_database.slt, testdata/sqllogictests_clickhouse/external_table.slt, testdata/sqllogictests_clickhouse/large_table.slt, testdata/sqllogictests_clickhouse/read.slt, testdata/sqllogictests_clickhouse/validation.slt
Adds support for clickhouse as a data source.
`read_clickhouse`:
```
> select * from read_clickhouse('clickhouse://localhost:9000/default', 'bikeshare_stations') limit 1;
┌────────────┬──────────┬────────┬─────────┬───┬─────────────────┬───────┬──────────────────┬───────────────────┐
│ station_id │ name     │ status │ address │ … │ footprint_width │ notes │ council_district │ modified_date     │
│         ── │ ──       │ ──     │ ──      │   │              ── │ ──    │               ── │ ──                │
│      Int32 │ Utf8     │ Utf8   │ Utf8    │   │         Float32 │ Utf8  │            Int32 │ Timestamp<s, UTC> │
╞════════════╪══════════╪════════╪═════════╪═══╪═════════════════╪═══════╪══════════════════╪═══════════════════╡
│          0 │ South C… │ active │ 1901 S… │ … │ …
```
=> feat: Clickhouse data source

crates/object_store_util/src/conf.rs, crates/sqlexec/src/engine.rs
```
$ AZURE_STORAGE_ACCOUNT_NAME=... \
AZURE_STORAGE_ACCOUNT_KEY=... \
glaredb --location "azure://vaibhav-test/path/to/db"
GlareDB (v0.7.1)
Persisting database at location: azure://vaibhav-test/path/to/db
>
```
```
$ glaredb --location "azure://vaibhav-test/path/to/db" \
--option "account_name=..." \
--option "access_key=..."
GlareDB (v0.7.1)
Persisting database at location: azure://vaibhav-test/path/to/db
>
```
=> feat: Add support for Azure data dir

.gitignore, crates/glaredb/src/commands.rs, crates/object_store_util/src/conf.rs, crates/sqlexec/src/engine.rs, crates/sqlexec/src/errors.rs
=> Revert "chore: Make bucket name required in storage config"

crates/datasources/src/bson/schema.rs, crates/datasources/src/bson/table.rs, crates/datasources/src/mongodb/infer.rs, testdata/sqllogictests_mongodb/external_database.slt
This pulls out the fix from #2318 for the fact that all numbers get
pushed into floats.
I also bundled a fix that does some more lazy parsing of the bson. 
This should definitely go into the next release whereas #2318 probably
won't make the cut.
=> fix: bson type inference fixes

crates/datafusion_ext/src/errors.rs, crates/sqlbuiltins/src/functions/table/object_store.rs, testdata/csv/delimiter.csv, testdata/sqllogictests/functions/read_csv.slt
```
> select * from read_csv('./testdata/csv/delimiter.csv', delimiter => ';');
┌───────┬──────────────┬─────────┐
│  col1 │ col2         │    col3 │
│    ── │ ──           │      ── │
│ Int64 │ Utf8         │ Float64 │
╞═══════╪══════════════╪═════════╡
│     1 │ hello, world │ 3.90000 │
│     2 │ HELLO, WORLD │ 4.90000 │
└───────┴──────────────┴─────────┘
```
Depends on https://github.com/GlareDB/glaredb/pull/2364
Adds the plumbing for getting options from the user in our various scan functions. The only one wired up right now is 'delimiter' for csv, but other options should be very straightforward to add in now.
=> feat: Allow specifying alt delimiter when reading csv

crates/metastore/src/database.rs, crates/sqlbuiltins/src/functions/mod.rs, crates/sqlbuiltins/src/functions/scalars/mod.rs, crates/sqlbuiltins/src/functions/scalars/postgres.rs, crates/sqlbuiltins/src/functions/table/object_store.rs, crates/sqlexec/src/dispatch/mod.rs, crates/sqlexec/src/planner/context_builder.rs, testdata/sqllogictests/catalog/functions.slt, testdata/sqllogictests/functions/arrow_cast.slt
- Adds back in examples/descriptions for some of the read_* functions
- Adds some tests asserting that we're actually getting entries in the functions table.
- Fixes panic when using non-table function as a table factor.
=> chore: Misc builtin function refactoring

crates/metastore/src/database.rs, crates/sqlbuiltins/src/functions/alias_map.rs, crates/sqlbuiltins/src/functions/mod.rs, crates/sqlbuiltins/src/functions/table/mod.rs, testdata/sqllogictests/catalog/functions.slt
Closes https://github.com/GlareDB/glaredb/issues/2368
Futzing around with function aliases. This replaces `HashMap` with `AliasMap` to allow multiple keys to point to the same object. Also adds some tests.
I needed to add a workaround for 'array_to_string' for one of the iterators, see https://github.com/GlareDB/glaredb/issues/2371.
=> chore: Add alias map for functions

crates/sqlbuiltins/src/functions/table/excel.rs
closes #2373 
```sql
> select function_name, parameters from glare_catalog.functions WHERE function_name = 'read_excel';
┌───────────────┬─────────────────────────────────────────────────────────────────────────┐
│ function_name │ parameters                                                              │
│ ──            │ ──                                                                      │
│ Utf8          │ List<Utf8>                                                              │
╞═══════════════╪═════════════════════════════════════════════════════════════════════════╡
│ read_excel    │ [Utf8, Utf8, sheet_name: Utf8, infer_rows: UInt64, has_header: Boolean] │
└───────────────┴─────────────────────────────────────────────────────────────────────────┘
```
=> fix: add signature for read_excel

testdata/sqllogictests/catalog/tables.slt
If we end up refacting builtin tables, this test just lets us do so without worrying about if we broke an oid.
=> chore: Add slt for asserting builtin tables

crates/datasources/src/common/util.rs, crates/datasources/src/sqlserver/errors.rs, crates/datasources/src/sqlserver/mod.rs
=> fix: Pushdown SQL Server `WHERE` clause

Cargo.lock, crates/glaredb/Cargo.toml, crates/glaredb/build.rs, crates/glaredb/src/commands.rs, crates/glaredb/src/lib.rs
closes https://github.com/GlareDB/glaredb/issues/2280
now it'll show a nice git version instead of just the pkg version. 
```sh
> ./glaredb
GlareDB (v0.8.0-11-g167702f)
```
you can read more about how the {git_version} is generated [here](https://docs.rs/built/0.7.1/built/#git2). 
TLDR; it uses the head (if its a tag, it uses just that, otherwise it uses a concatonation of the last tag + the commit)
It does cache this in your `target` dir, so if it's not showing the current commit, it's likely that this generated file is cached.
=> add commit-sha to cli

justfile
Since that crate no longer exists.
=> chore: Remove `--exclude testing` from justfile

crates/datasources/src/postgres/errors.rs, crates/datasources/src/postgres/mod.rs
```
> select * from pg.public.comments;
Error: External error: External error: Overflow converting '0001-01-01 00:00:00 UTC' to Timestamp(Nanosecond, Some("UTC"))
```
Fixes: #2412
=> fix: Error instead of panic when converting pg timestamps to arrow

Cargo.lock, crates/datasources/Cargo.toml, crates/slt/Cargo.toml
Was causing build failures on windows. Didn't seem to be used anyways.
Note that we conditionally use openssh in the datasources crate to get around this:
```
[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
openssh = "0.10.2"
```
=> chore: Remove openssh from slt crate cargo.toml

.github/workflows/ci.yaml, scripts/create-test-minio-store.sh
I'm trying to make the ci more debuggable & [this](https://github.com/GlareDB/glaredb/actions/runs/7547162039/job/20547603632?pr=2415) is just stalling. Not really sure where. The last logs indicate that it may be near the minio stuff, so pulling this out to make future pipelines more debuggable. 
also runs the minio tests over the flight protocol.
=> ci: move minio into its own job

CONTRIBUTING.md, Cargo.lock, crates/datafusion_ext/Cargo.toml, crates/datafusion_ext/src/vars.rs, crates/datafusion_ext/src/vars/constants.rs, crates/datafusion_ext/src/vars/inner.rs, crates/datafusion_ext/src/vars/value.rs, crates/glaredb/src/local.rs, crates/pgprototest/src/main.rs, crates/pgprototest/src/messages.rs, crates/pgprototest/src/proto.rs, crates/pgrepr/src/error.rs, crates/pgrepr/src/lib.rs, crates/pgrepr/src/notice.rs, crates/pgsrv/src/handler.rs, crates/pgsrv/src/messages.rs, crates/sqlexec/src/context/local.rs, crates/sqlexec/src/session.rs, scripts/protocol-test.sh, testdata/pgprototest_glaredb/transactions.pt, testdata/sqllogictests/functions/postgres.slt, testdata/sqllogictests/transactions.slt, testdata/sqllogictests/vars.slt
Emit notices on transaction commands warning about our incomplete transaction support.
psql:
```
sean@Seans-Air glaredb % psql postgres://localhost:6543
psql (15.4, server 15.1)
Type "help" for help.
sean=> begin;
WARNING:  GlareDB does not support proper transactional semantics. Do not rely on transactions for correctness. Transactions are stubbed out to enable compatability with existing Postgres tools.
BEGIN
sean=> 
```
CLI (colorful):
Some pg protocol tests added to assert the notices.
=> feat: Notices on transactions

crates/glaredb/tests/iss_2309.rs, crates/glaredb/tests/local_args_test.rs, crates/glaredb/tests/log_file_test.rs, crates/glaredb/tests/output_mode_test.rs, crates/glaredb/tests/server_args_test.rs, crates/glaredb/tests/setup.rs
Partially addresses https://github.com/GlareDB/glaredb/issues/2467
=> chore: Remove timeouts from CLI tests that don't need them

Cargo.lock, bindings/nodejs/Cargo.toml, bindings/nodejs/src/execution_result.rs, bindings/python/Cargo.toml, bindings/python/src/execution_result.rs, crates/README.md, crates/arrow_util/Cargo.toml, crates/arrow_util/src/pretty.rs, crates/glaredb/Cargo.toml, crates/glaredb/src/local.rs, crates/terminal_util/Cargo.toml, crates/terminal_util/src/lib.rs
Ensures crossterm isn't a dependency of arrow_util. Also disables default features for `comfy_term` since we're not using their terminal detection stuff (which uses crossterm).
=> chore: Split out term width function into its own crate

crates/sqlbuiltins/src/builtins.rs, testdata/sqllogictests/pg_catalog.slt
closes https://github.com/GlareDB/glaredb/issues/2475
We were incorrectly calling the table `pg_table` when it is supposed to be `pg_tables`
=> fix: rename "pg_table" to "pg_tables"

CONTRIBUTING.md
=> chore: update contributing with pytest info

.github/workflows/ci.yaml, crates/datasources/src/clickhouse/convert.rs, crates/datasources/src/clickhouse/mod.rs, crates/rpcsrv/src/flight/handler.rs, crates/sqlexec/src/session.rs
TBH, I am not sure exactly what fixed this but during my investigation I realized, something in flight + clickhouse implementation messes up the stream and eats it up even before it's executed. This is "technically" correct and works!
Fixes: #2389
=> fix: Execute clickhouse query in stream (during execution)

scripts/create-test-cassandra-db.sh, scripts/images/cassandra/Dockerfile, scripts/images/cassandra/cassandra.yaml, testdata/sqllogictests_cassandra/basic.slt, testdata/sqllogictests_cassandra/external_database.slt, testdata/sqllogictests_cassandra/external_table.slt, testdata/sqllogictests_cassandra/read.slt, testdata/sqllogictests_cassandra/supported_dtypes.slt, testdata/sqllogictests_cassandra/validation.slt
This builds on top of #2478 and shouldn't merge until after that does.
This configures our cassandra test fixture to require auth. It just uses the default passwordAuthenticator, and only has the default superuser role (username = cassandra, password = cassandra).
Adding this in means we don't have a test for the "unauthenticated". To add a test for the "unauthenticated" scenario would be a bit of a pain given how it's configured through `cassandra.yaml` and requires node restarts. If we do add in a test for that scenario, I'd suggest creating a second cassandra container that doesn't mount in our custom `cassandra.yaml` and running a really basic smoke test, since the only thing we're testing that alters from the auth tests is that we can create data sources and use our table func …
=> test(cassandra): require auth

.github/workflows/ci.yaml
=> Revert "chore: enable ci for merge queue events"

crates/sqlbuiltins/src/builtins.rs, testdata/sqllogictests/pg_catalog.slt
@talagluck this should fix the great-expectations issue you referenced in https://github.com/GlareDB/glaredb/issues/2436
=> fix: add pg_matview table

.github/workflows/ci.yaml, scripts/protocol-test.sh
This (on top of #2518) should get wall clock time to about 10 minutes for an entire PR run, at the same cost. 
It's likely redundant to the other suite. We could also switch datasource integration to just postgres as there's less postgres protocol coverage.
=> chore: skip sqlserver+flight combination.

.github/workflows/ci.yaml
(this has a restriction commented out for testing, which I'll remove before merging.)
Basically this helps us populate a shareable cache (so that PRs can
get access to relatively fresh base caches and avoid slow first
builds.)
=> chore: populate shareable cache on main

.github/workflows/pr-cleanup.yaml
(this is hard to check before merge for obvious reasons)
=> chore: ci clean up caches after a PR merges

crates/datasources/src/object_store/http.rs
reqwest's `content_length` method apparantly doesnt check for the casing of "Content-Length". This seems like a bug in reqwest to me. 
https://github.com/seanmonstar/reqwest/issues/843
```rust
#[tokio::main]
async fn main() {
let client = reqwest::Client::new();
let head_res = client.head("https://clickhouse-public-datasets.s3.eu-central-1.amazonaws.com/hits_compatible/athena/hits.parquet").send().await.unwrap();
let content_length = head_res.content_length();
assert_eq!(content_length, Some(14779976446))
}
```
closes https://github.com/GlareDB/glaredb/issues/2561
=> fix: parquet over http 

crates/proxyutil/src/cloudauth.rs
These are harmless to have around in the tests, but don't add value and may mislead someone in the future into expecting they exist on the actual response
=> chore(cloudauth): remove unused fields

crates/datasources/src/bson/builder.rs, crates/datasources/src/bson/mod.rs, testdata/sqllogictests_object_store/local/bson.slt
=> fix: bson timestamp type casting

crates/sqlbuiltins/src/builtins.rs, testdata/sqllogictests/pg_catalog.slt
These are to make another step toward fixing #2436. 
I built the definitions off of https://www.postgresql.org/docs/16/catalog-pg-depend.html and https://www.postgresql.org/docs/16/catalog-pg-rewrite.html, but please double-check that I did this correctly.
=> fix: add pg_rewrite and pg_depend tables

crates/metastore/src/database.rs, crates/metastore/src/lib.rs, crates/metastore/src/storage/lease.rs, crates/metastore/src/storage/persist.rs, crates/sqlbuiltins/src/builtins.rs, crates/sqlbuiltins/src/validation.rs, crates/sqlexec/src/context/local.rs, crates/sqlexec/src/planner/context_builder.rs
Summary
---
This adds a restriction in metastore for creating entries on builtin schemas, other than the default schema (`public`).
<details><summary>Details</summary>
<p>
Initially, this added a builtin schema `glare_uploads` (#2614), but we later decided to remove it and instead use a table funcition.
At the time, `glare_uploads` was chosen because prefixing internal schemas with `glare_` reduces collision chance, and is what pg does.
<details><summary>Read more on pg_</summary>
<p>
From https://www.postgresql.org/docs/current/ddl-schemas.html
> Since system table names begin with pg_, it is best to avoid such names to ensure that you won't suffer a conflict if some future version defines a system table named the same as your table. (With the default search path, an unqualified …
=> fix(metastore): make builtin schemas readonly

crates/datasources/src/native/access.rs, testdata/sqllogictests/datatypes.slt
Fixes #2588 
As Unsigned integers are downgraded to integers when stored in delta-lake. Adding metadata.
@universalmind303 This is similar to #2607 Kindly review.
Thanks,
=> Fix: Unsigned integer types being cast to integers

crates/sqlbuiltins/src/functions/table/virtual_listing.rs
A very minor fix to df signature implementations for `list_schemas` (missing) and `list_tables` (wrong len) that I found while working on something else.
=> fix(virtual_listing): signatures

.github/workflows/ci.yaml
We are no longer getting updates to the `main` tag
=> chore(ci): build images from 'main'

crates/glaredb/src/args/local.rs, crates/glaredb/src/args/mod.rs, crates/glaredb/src/args/server.rs
Sort of a drive-by clean up while working on something else. I'm not actively looking for these refactors, but I'm just kind of finding things that stick out to me while working through different areas of the cb for more holistic tasks.
=> chore(args): refactor imports

.github/workflows/ci.yaml, crates/glaredb/src/args/slt.rs, crates/slt/src/hooks.rs, crates/slt/src/test.rs
I started with the intention of just having the postgres tasks in
their test, but took the oppertunity to:
- clarify some capitalization that was bugging me (since I'll need to
update the required builders, which are keyed off of this string).
- while I was editing this I realized that `tunnes/ssh` tests which we
go through a lot of trouble to test with/without, are only present
for mysql and postgres, and the only reason to skip running the
tunnel tests, given the execution of the SLT runner and the hooks,
is to omit running the `basic.slti` an extra time (but only for
mysql/postgres), and given the new test architecture I think its
safe to dispense with (and the invocations were redundnat in the
main case.)
=> chore(ci): move postgres tests and simplify tunnels testing

Cargo.lock, Cargo.toml, crates/datafusion_ext/Cargo.toml, crates/datasources/Cargo.toml, crates/pgrepr/Cargo.toml, crates/pgsrv/Cargo.toml, crates/sqlexec/Cargo.toml
Closes #2667
Closes #2666
Closes #2665
Closes #2664
Closes #2663
Closes #2662
Closes #2661
Closes #2660
Closes #2659
Closes #2658
=> chore: dependency upgrade for 2024-02-16

crates/datafusion_ext/src/planner/relation/mod.rs
Duplicated match arm (dead code) causing lint failure in CI (see: https://github.com/GlareDB/glaredb/actions/runs/7991177287/job/21822034352)
=> chore(infer_func_for_file): remove dead code

crates/datafusion_ext/src/planner/relation/mod.rs, crates/metastore/src/database.rs, testdata/sqllogictests/alter.slt
=> fix: Alter table renames view successfully

crates/glaredb/src/local.rs
Resolves: #2549 
This shows time elapsed where it matters, For commands like COPY, INSERT, DELETE  and UPDATE.
Please suggest changes if any.
Thanks
=> fix: report time display for DDL commands

.github/workflows/ci.yaml
=> chore: reduce caching overhead for build steps

crates/protogen/src/metastore/types/options.rs, crates/protogen/src/sqlexec/copy_to.rs, crates/sqlexec/src/optimizer.rs, crates/sqlexec/src/planner/physical_plan/copy_to.rs, crates/sqlexec/src/planner/session_planner.rs
Realized this was missing during review of #2634
=> chore: make bson copy to options more consistent

crates/datasources/src/excel/errors.rs, crates/datasources/src/excel/mod.rs, crates/datasources/src/excel/stream.rs, crates/datasources/src/excel/table.rs, crates/datasources/src/json/stream.rs, crates/sqlexec/src/dispatch/external.rs, crates/sqlexec/src/dispatch/mod.rs, crates/sqlexec/src/planner/session_planner.rs, testdata/sqllogictests/xlsx.slt
closes https://github.com/GlareDB/glaredb/issues/2644, summary of changes:
- implements the `create external table excel <options>` sql command by adding a "streaming table" interface that maps excel rows/columns into a `RecordBatch`.
this will likely be superseded with a followup after the `TableProvider` is implemented for (https://github.com/GlareDB/glaredb/issues/2645) to allow querying on tables and it's missing support for streaming multiple sheets from a worksheet, it's also not super optimal quite yet, but happy to iterate on it on this pr or a followup.
=> feat: support for `create external table excel <options>`

crates/catalog/src/mutator.rs, crates/glaredb/src/highlighter.rs, crates/metastore/src/database.rs, crates/protogen/proto/metastore/catalog.proto, crates/protogen/proto/metastore/service.proto, crates/protogen/src/metastore/types/catalog.rs, crates/protogen/src/metastore/types/service.rs, crates/rpcsrv/src/session.rs, crates/sqlbuiltins/src/functions/mod.rs, crates/sqlbuiltins/src/functions/scalars/similarity.rs, crates/sqlbuiltins/src/functions/table/lance.rs, crates/sqlexec/src/context/local.rs, crates/sqlexec/src/context/remote.rs, crates/sqlexec/src/dispatch/external.rs, crates/sqlexec/src/dispatch/mod.rs, crates/sqlexec/src/dispatch/system.rs, crates/sqlexec/src/planner/context_builder.rs, crates/sqlexec/src/session.rs
I didn't want to create 1 massive undecipherable PR, so I wanted to submit this first. 
This ties a `FunctionRegistry` instance to a session instead of the previously global `FUNCTION_REGISTRY`. 
Right now, the entries are written to both the catalog and the function registry. 
I'd prefer writing to just one or the other, but havent quite figured that out yet as our udfs are not serializable so they cant be written directly to the catalog. 
Some other the notable changes so far
- some catalog changes to allow for adding new user defined functions to the catalog.
- internally to expose a new method `register_function` on the session. 
- rework `cosine_similarity` to the new datafusion udf impl pattern for easier usage with the new `register_function` method.
I manually tested this by …
=> refactor: extensible function registry

Cargo.lock, crates/datasources/Cargo.toml, crates/sqlbuiltins/Cargo.toml
lance uses duckdb as a submodule, and it's a pretty massive repo, `555.9 MB` on a fresh clone. It currently takes absolutely forever to build glaredb the first time _(or subsequent times if you nuke your cargo cache)_.
`git clone https://github.com/duckdb/duckdb.git` alone takes almost 4 minutes locally. 
this just forks lance and removes the submodule to avoid the problem alltogether.
=> chore: use a lance fork without the duckdb submodule

tests/test_bson.py
This was fixed a while ago, but adding more regression coverage for
#2408.
Closes #2408
=> chore: add relative path regression test

bindings/python/tests/test_connection.py, bindings/python/tests/test_logical_plan.py
=> chore: cleanup in python bindings tests

crates/sqlexec/src/dispatch/external.rs
Closes #2405
We put the filetype in this error message if we have it, and we'd
previously put in the path so users can deduce what's up in the case
that they're running an external table from an object store provider.
=> fix: error string clarifying quotes

crates/sqlbuiltins/src/functions/table/delta.rs, crates/sqlbuiltins/src/functions/table/iceberg/scan.rs, crates/sqlbuiltins/src/functions/table/lance.rs, testdata/sqllogictests/functions/delta_scan.slt, testdata/sqllogictests_iceberg/local_v2.slt, testdata/sqllogictests_object_store/local/lance.slt
- `lance_scan` -> `read_lance`
- `iceberg_scan` -> `read_iceberg`
- `delta_scan` -> `read_delta`
=> feat: add some table aliases for lance,iceberg and delta

Cargo.lock, Cargo.toml, crates/datasources/src/cassandra/builder.rs, crates/datasources/src/common/util.rs, crates/datasources/src/excel/mod.rs, crates/datasources/src/mysql/mod.rs, crates/datasources/src/postgres/mod.rs, crates/datasources/src/sqlite/convert.rs, crates/datasources/src/sqlserver/mod.rs, crates/glaredb/Cargo.toml, crates/pgrepr/src/scalar.rs, crates/pgrepr/src/writer.rs, crates/pgsrv/Cargo.toml, crates/repr/src/str/encode.rs, crates/rpcsrv/Cargo.toml, crates/slt/Cargo.toml, crates/snowflake_connector/Cargo.toml, crates/snowflake_connector/src/auth.rs, crates/sqlbuiltins/Cargo.toml
Closes #2757
Closes #2758
Closes #2759
Closes #2760
Closes #2761
Closes #2762
Closes #2763
Closes #2764
Closes #2765
=> chore: upgrade dependencies

crates/metastore/src/storage/lease.rs, crates/metastore/src/storage/mod.rs
This should fix the issue. We are retrying here as suggested by GCS since writing the same object again and again is rate limited to once per second.
Another thing that might help is writing to a new "temp" object every time (instead of using the same one for the same process).
Fixes: https://github.com/GlareDB/cloud/issues/2746
=> fix: Retry writing lease when error code 429 (too many requests).

crates/datasources/src/json/table.rs, crates/sqlbuiltins/src/functions/table/json.rs
This is the same implementation as in the BSON, need to have an
external table connection to wire this up directly.
=> chore: add explicit schema support for json streaming

crates/metastore/src/storage/lease.rs, crates/metastore/src/storage/mod.rs
The temp path is generated with a random UUID as suffix.
=> chore: Create a new temp object when writing lease all the time.

crates/catalog/src/session_catalog.rs, crates/sqlexec/src/remote/client.rs, crates/sqlexec/src/resolve.rs
closes #2779 
Note for Reviewers: 
There isn't a real good way that I know of to add a test for this, so i will just share the steps I took to manually test it. 
1. go to console.glaredb.com
2. create a view in there: `create view "my_view" as select 1;`
3. connect to cloud via local
```sh
> just run local
> \open glaredb://<USER>:<PASS>@o_xTz3cuY.remote.glaredb.com:6443/quiet_frog
Connected to Cloud deployment (TLS enabled): quiet_frog
> select * from "quiet_frog"."public"."my_view";
┌──────────┐
│ Int64(1) │
│       ── │
│    Int64 │
╞══════════╡
│        1 │
└──────────┘
```
it also works the other way around. Previously a create statement `create view quiet_frog.public.my_view_2` would save it to the "default" db, now it properly saves it under the alias name
```sql
> create view …
```
=> fix: resolve aliased catalogs

crates/datasources/src/lake/mod.rs, crates/datasources/src/object_store/http.rs, crates/sqlbuiltins/src/functions/table/mod.rs, testdata/sqllogictests/http.slt
=> fix: Allow HTTP object store for json/bson etc.

flake.lock, flake.nix
Other nix/rust libs have fancier caching... but this has the advantage of being portable to upstream nixos/nixpkgs.
I've tested this on `x86_64-linux`.
```console
$ nix build
$ ./result/bin/glaredb
GlareDB (v0.9.0)
>
```
=> feat: add nix derivation

crates/catalog/src/session_catalog.rs, crates/sqlexec/src/engine.rs
closes https://github.com/GlareDB/glaredb/issues/2779
manually tested in cloud via:
```sql
create view "broken_sky"."public"."my_view" as select 1;
```
```sql
select * from "broken_sky"."public"."my_view";
```
=> fix: properly alias all sessions

bindings/nodejs/package.json
According to the print out here: https://github.com/GlareDB/glaredb/actions/runs/8363511181/job/22898484272#step:10:27
`napi` doesn't accept any args (`=true` in this case) for boolean flags.
=> chore(npm): fix napi argument

.github/workflows/ci.yaml
While investigating and debugging #2805, I found myself confused by
the way the output was organized. This should clarify things a bit.
=> chore: organize output for mino test results

crates/datafusion_ext/src/metrics.rs, crates/datafusion_ext/src/runtime/runtime_group.rs, crates/sqlexec/src/planner/physical_plan/copy_to.rs, testdata/sqllogictests/copy_to.slt
closes https://github.com/GlareDB/glaredb/issues/2811
=> fix: properly satisfy enforcesorting rules

crates/datasources/src/object_store/azure.rs, crates/datasources/src/object_store/gcs.rs, crates/datasources/src/object_store/s3.rs
GCS works (raising a PR for NULL Credentials):
```
> select * from 'gs://vrongmeal-public-test/data.csv';
┌───────┬─────────┐
│    id │ name    │
│    ── │ ──      │
│ Int64 │ Utf8    │
╞═══════╪═════════╡
│     1 │ vaibhav │
│     2 │ sean    │
│     3 │ grey    │
└───────┴─────────┘
```
Need to make a similar change upstream for S3 and Azure.
Fixes: #1065
=> fix: Support null credentials for object store access.

.github/workflows/ci.yaml
This moves the bigquery task out of the "service integration test,"
leaving only object store-specific tasks in the big group task. This
is probably mostly for clarity and ease of reporting, and won't really
impact running time or cost.
=> chore: isolate bigquery task in CI

testdata/sqllogictests/http.slt
(this is failing in a number of orthogonal open PRs. verified that the
result is correct without using glaredb.) wanted to make a PR for only
this change just to create a paper trail for this one.
=> fix: non-deterministic http test

Cargo.lock, bindings/nodejs/index.d.ts, bindings/nodejs/src/connection.rs, bindings/python/src/connect.rs, bindings/python/src/connection.rs, bindings/python/src/lib.rs, bindings/python/tests/test_execution_model.py, crates/object_store_util/Cargo.toml, crates/object_store_util/src/conf.rs
This leads to confusing problems in the bindings.
Want to run this through CI, probably a couple of bindings tests will
break (and will be fixed.) Also need to update documentation of
bindings.
Closes #2867
=> fix: in memory db should not be global

crates/datasources/src/native/access.rs, testdata/sqllogictests/create_table.slt
closes https://github.com/GlareDB/glaredb/issues/2777
Note: 
`ident` preserves case sensitivity while `col` does not.
=> fix: case sensitive with cast for delta

.dockerignore, .gitignore
Occasionally, I like to use finder and it always creates these `.DS_Store` files. Best to just ignore them.
=> chore: ignore .DS_Store

crates/catalog/src/session_catalog.rs, crates/sqlexec/src/engine.rs, crates/sqlexec/src/resolve.rs
Previously we were doing some processing on the database name to try to extract out the "true" name from names that follow the "org/database" format. However that meant if someone connects to the db over postgres using a hostname like "proxy.glaredb.com/my_org/my_db", we would set the catalog alias to only "my_db", disallowing queries like `SELECT * FROM
"my_org/my_db"."my_schema"."my_table"` even though that's a valid query given the connect string.
This change makes the name returned from `SHOW database_name` consistent with the alias we set on the session catalog, allowing the previous query to work as expected.
=> fix: Don't preprocess database name when setting session catalog alias

Dockerfile
=> build: Make sure docker image has cmake during build

crates/datasources/src/excel/mod.rs, crates/datasources/src/excel/table.rs, crates/protogen/proto/metastore/options.proto, crates/protogen/src/metastore/types/options.rs, crates/sqlbuiltins/src/functions/table/excel.rs, crates/sqlexec/src/dispatch/external.rs, crates/sqlexec/src/planner/session_planner.rs, testdata/sqllogictests/xlsx.slt
We previously had different dispatching and validation rules for
`read_excel` and other tables. This should make the code paths more
similar for the table function and the external tables.
@talagluck maybe worth adding some more tests to this one
=> fix: excel table function should read data more consistently from remote sources

crates/datasources/src/bson/builder.rs, crates/datasources/src/bson/errors.rs, crates/datasources/src/bson/schema.rs, crates/datasources/src/bson/stream.rs
This removes a todo, and lets things be more consistent. 
Handling of array/docs to string (as json) or binary, (which would
only be possible in an explicit schema situation,) let's GlareDB avoid
more expensive processing.
=> feat: nested bson constructs (array and document) should always be structures

crates/datasources/src/bson/table.rs
I was looking through the code to see if it would be reasonable to
convert BSON to JSON and then filter with `jaq` as recently added to
json documents and saw these cleanups. 
The answer to the `jaq` questions is "it's possible, but it would slow
things down a bunch, in a way that I'm not comfortable doing." It has
inspried me to add a `bson_to_json()` (string) converter for binary
fields, and improve type conversion a bit for nested fields.
=> chore: bson stream cleanup

crates/datasources/src/bson/builder.rs, crates/datasources/src/bson/errors.rs, crates/datasources/src/common/util.rs, crates/datasources/src/sqlite/convert.rs
handling some more string value and timestamp conversion endge cases.
=> chore: cleanup some timestamp handling, mostly in bson

Cargo.lock, crates/sqlbuiltins/Cargo.toml, crates/sqlbuiltins/src/errors.rs, crates/sqlbuiltins/src/functions/mod.rs, crates/sqlbuiltins/src/functions/scalars/bson2json.rs, crates/sqlbuiltins/src/functions/scalars/jaq.rs, crates/sqlbuiltins/src/functions/scalars/kdl.rs, crates/sqlbuiltins/src/functions/scalars/mod.rs, testdata/sqllogictests/functions/bson.slt
This still needs tests, but makes bson values easier to produce
(e.g. from json, etc.) and then also (optionally) manipulate using the
`jaq_<->` functions.
=> feat: bson2json and json2bson scalar converters

crates/datasources/src/json/errors.rs, crates/datasources/src/json/stream.rs, crates/datasources/src/json/table.rs
=> fix: clearer error handling around nested arrays

bindings/python/src/error.rs, bindings/python/tests/test_execution_model.py, crates/glaredb/src/lib.rs, crates/pgrepr/src/notice.rs, crates/sqlexec/src/session.rs
This restores the legacy semantics (ish) but caches the results for eagerly executed options so that calling the resolving methods (e.g. `to_pandas()`) won't error in the case of rexecution.
This will be weird in cases where `INSERT INTO foo VALUES(123, now()) "tick-tock")`, which you might expect to insert more than one row if it were being lazily evaluated in the old way.
=> fix: clarify evaluation semantics for DDL operations in bindings

Cargo.lock, Cargo.toml, crates/snowflake_connector/Cargo.toml, crates/sqlbuiltins/Cargo.toml, crates/terminal_util/Cargo.toml
Closes: #3221
Closes: #3220
Closes: #3219
Closes: #3218
Closes: #3217
Closes: #3216
=> chore(deps): rust update batch

crates/rayexec_execution/src/logical/binder/bind_context.rs, crates/rayexec_execution/src/logical/binder/bind_query/select_expr_expander.rs, crates/rayexec_execution/src/logical/resolver/expr_resolver.rs, crates/rayexec_parser/src/ast/select.rs, crates/rayexec_parser/src/keywords.rs, slt/standard/select/exclude_except.slt, slt/standard/select/replace.slt
Omit columns from the out of a `select *`
```
>> CREATE TEMP TABLE t1 (a INT, b INT, c INT);
│ Query success       │
│ No columns returned │
>> INSERT INTO t1 VALUES (2,3,4);
┌───────────────┐
│ rows_inserted │
│ UInt64        │
├───────────────┤
│             1 │
└───────────────┘
>> SELECT * EXCLUDE (b) FROM t1;
┌───────┬───────┐
│ a     │ c     │
│ Int32 │ Int32 │
├───────┼───────┤
│     2 │     4 │
└───────┴───────┘
```
Replace columns in the output of a `select *`
```
>> CREATE TEMP TABLE t1 (a INT, b INT, c INT);
│ Query success       │
│ No columns returned │
>> INSERT INTO t1 VALUES (2,3,4);
┌───────────────┐
│ rows_inserted │
│ UInt64        │
├───────────────┤
│             1 │ …
```
=> feat: EXCLUDE/EXCEPT and REPLACE wildcard modifiers

crates/rayexec_execution/src/logical/binder/bind_query/select_expr_expander.rs, crates/rayexec_execution/src/logical/binder/expr_binder.rs, crates/rayexec_execution/src/logical/resolver/expr_resolver.rs, crates/rayexec_parser/src/ast/expr.rs, crates/rayexec_parser/src/keywords.rs, slt/standard/select/columns.slt
Supports selecting columns by regex.
```
>> CREATE TEMP TABLE t1 (col_a INT, col_b INT, col_c INT, other INT);
│ Query success       │
│ No columns returned │
>> INSERT INTO t1 VALUES (2,3,4,5);
┌───────────────┐
│ rows_inserted │
│ UInt64        │
├───────────────┤
│             1 │
└───────────────┘
>> SELECT COLUMNS('col_*') FROM t1;
┌───────┬───────┬───────┐
│ col_a │ col_b │ col_c │
│ Int32 │ Int32 │ Int32 │
├───────┼───────┼───────┤
│     2 │     3 │     4 │
└───────┴───────┴───────┘
```
=> feat: COLUMNS('regex') expression in select list

crates/rayexec_bullet/src/executor/aggregate/mod.rs, crates/rayexec_execution/src/execution/intermediate/planner.rs, crates/rayexec_execution/src/execution/operators/mod.rs, crates/rayexec_execution/src/execution/operators/unnest.rs, crates/rayexec_execution/src/explain/formatter.rs, crates/rayexec_execution/src/expr/mod.rs, crates/rayexec_execution/src/expr/unnest_expr.rs, crates/rayexec_execution/src/logical/binder/expr_binder.rs, crates/rayexec_execution/src/logical/logical_unnest.rs, crates/rayexec_execution/src/logical/mod.rs, crates/rayexec_execution/src/logical/operator.rs, crates/rayexec_execution/src/logical/planner/mod.rs, crates/rayexec_execution/src/logical/planner/plan_select.rs, crates/rayexec_execution/src/logical/planner/plan_unnest.rs, crates/rayexec_execution/src/logical/resolver/expr_resolver.rs, crates/rayexec_execution/src/logical/resolver/resolved_function.rs, slt/standard/select/unnest.slt
Initial UNNEST support.
Basic list unnest:
```
>> SELECT unnest([3,4,5]);
┌────────┐
│ unnest │
│ Int32  │
├────────┤
│      3 │
│      4 │
│      5 │
└────────┘
```
Unnests with different list lengths:
```
>> SELECT unnest([3,4,5]), unnest([3,2]);
┌────────┬────────┐
│ unnest │ unnest │
│ Int32  │ Int32  │
├────────┼────────┤
│      3 │      3 │
│      4 │      2 │
│      5 │   NULL │
└────────┴────────┘
```
Aggregate list values using unnest:
```
>> SELECT sum(unnest(a)), min(unnest(a)), max(unnest(a)) FROM VALUES ([1,2,3]), ([4,5,6]) v(a);
┌───────┬───────┬───────┐
│ sum   │ min   │ max   │
│ Int64 │ Int32 │ Int32 │
├───────┼───────┼───────┤
│    21 │     1 │     6 │
└───────┴───────┴───────┘
```
=> feat: UNNEST in select list

Cargo.lock, Cargo.toml, bench/standard/min_max_generate_series_10M.bench, bench/standard/select_1.bench, bench_bin/Cargo.toml, bench_bin/bench_standard.rs, crates/rayexec_bench/Cargo.toml, crates/rayexec_bench/src/benchmark.rs, crates/rayexec_bench/src/lib.rs, crates/rayexec_bench/src/runner.rs
```
% cargo run -r --bin bench_standard
Finished `release` profile [optimized] target(s) in 0.13s
Running `target/release/bench_standard`
benchmark_name                                    count        time_ms
bench/standard/min_max_generate_series_10M            1             56
bench/standard/min_max_generate_series_10M            2             35
bench/standard/min_max_generate_series_10M            3             31
bench/standard/min_max_generate_series_10M            4             31
bench/standard/min_max_generate_series_10M            5             31
bench/standard/select_1                               1              0
bench/standard/select_1                               2              0
bench/standard/select_1                               3              0 …
```
=> chore: Benchmark framework

crates/rayexec_bullet/src/executor/scalar/fill.rs, crates/rayexec_bullet/src/executor/scalar/hash.rs, crates/rayexec_bullet/src/executor/scalar/list.rs, crates/rayexec_error/src/lib.rs, crates/rayexec_execution/src/execution/operators/unnest.rs, crates/rayexec_execution/src/functions/scalar/builtin/comparison.rs, crates/rayexec_execution/src/functions/scalar/builtin/similarity/l2_distance.rs, crates/rayexec_execution/src/functions/table/builtin/mod.rs, crates/rayexec_execution/src/functions/table/builtin/unnest.rs, crates/rayexec_execution/src/optimizer/column_prune.rs, slt/standard/functions/scalars/list_comparisons.slt, slt/standard/functions/table/unnest_list.slt
```
GlareDB Shell
Preview (0.0.91) - There will be bugs!
>> SELECT * FROM (VALUES ([1,2,3]), ([8,9])) v(a), unnest(v.a);
┌─────────────┬────────┐
│ a           │ unnest │
│ List[Int32] │ Int32  │
├─────────────┼────────┤
│ [1, 2, 3]   │      1 │
│ [1, 2, 3]   │      2 │
│ [1, 2, 3]   │      3 │
│ [8, 9]      │      8 │
│ [8, 9]      │      9 │
└─────────────┴────────┘
```
=> feat: Lateral unnest + additional list array logic

crates/rayexec_bullet/src/datatype.rs, crates/rayexec_bullet/src/storage/list.rs, crates/rayexec_execution/src/functions/table/builtin/system.rs
```
>> select * from list_functions() where function_name like '%trim';
┌───────────────┬───────────────┬───────────────┬───────────────┬────────────────┬──────────────────────┬─────────────┬─────────────────────────────────────────────────────────────┬──────────────────────────┬────────────────┐
│ database_name │ schema_name   │ function_name │ function_type │ argument_types │ argument_names       │ return_type │ description                                                 │ example                  │ example_output │
│ Utf8          │ Utf8          │ Utf8          │ Utf8          │ List[Utf8]     │ List[Utf8]           │ Utf8        │ Utf8                                                        │ Utf8                     │ Utf8           │ …
```
=> feat: More info in `list_functions` output

crates/rayexec_execution/src/config/session.rs, crates/rayexec_execution/src/engine/session.rs, crates/rayexec_execution/src/logical/binder/bind_query/bind_select_list.rs, crates/rayexec_execution/src/logical/binder/column_binder.rs, crates/rayexec_execution/src/logical/resolver/expr_resolver.rs, crates/rayexec_execution/src/logical/resolver/mod.rs, crates/rayexec_execution/src/logical/resolver/resolve_hybrid.rs, slt/standard/functions/chaining.slt, slt/standard/functions/qualified.slt, slt/standard/select/reference_alias_in_select.slt
```
>> CREATE TEMP TABLE t (a INT, b TEXT);
│ Query success       │
│ No columns returned │
>> INSERT INTO t VALUES (3, 'cat'), (4, 'dog'), (NULL, 'mouse'), (5, NULL);
┌───────────────┐
│ rows_inserted │
│ UInt64        │
├───────────────┤
│             4 │
└───────────────┘
>> SELECT b.upper() FROM t;
┌───────┐
│ upper │
│ Utf8  │
├───────┤
│ CAT   │
│ NULL  │
│ MOUSE │
│ DOG   │
└───────┘
>> SELECT t.b.upper() AS my_upper, my_upper.repeat(t.a) AS my_repeat, my_repeat.lower() AS my_lower FROM t;
┌──────────┬───────────┬──────────┐
│ my_upper │ my_repeat │ my_lower │
│ Utf8     │ Utf8      │ Utf8     │
├──────────┼───────────┼──────────┤
│ MOUSE    │ NULL      │ NULL     │
│ NULL     │ NULL      │ NULL     │
│ CAT      │ CATCATCAT │ catcatc… …
```
=> feat: Function dot syntax

Cargo.lock, crates/rayexec_execution/Cargo.toml, crates/rayexec_execution/src/functions/aggregate/states.rs, crates/stdutil/Cargo.toml, crates/stdutil/src/iter.rs, crates/stdutil/src/lib.rs, crates/stdutil/src/marker.rs
=> chore: Add stdutil crate

crates/rayexec_execution/src/arrays/array/mod.rs, crates/rayexec_execution/src/arrays/batch.rs, crates/rayexec_execution/src/arrays/format/pretty/table.rs, crates/rayexec_execution/src/execution/intermediate/planner/plan_scan.rs, crates/rayexec_execution/src/execution/operators/filter.rs, crates/rayexec_execution/src/execution/operators/hash_join/condition.rs, crates/rayexec_execution/src/execution/operators/hash_join/global_hash_table.rs, crates/rayexec_execution/src/execution/operators/limit.rs, crates/rayexec_execution/src/execution/operators/nl_join.rs, crates/rayexec_execution/src/execution/operators/util/outer_join_tracker.rs, crates/rayexec_execution/src/execution/operators/util/resizer.rs, crates/rayexec_execution/src/expr/physical/case_expr.rs, crates/rayexec_execution/src/storage/table_storage.rs, crates/rayexec_shell/src/result_table.rs
Split from mutable buffers branch
=> chore: Add more batch methods

Cargo.lock, crates/ext_spark/Cargo.toml, crates/ext_spark/src/functions/csc.rs, crates/ext_spark/src/functions/expm1.rs, crates/ext_spark/src/functions/mod.rs, crates/ext_spark/src/lib.rs, crates/glaredb/Cargo.toml, crates/glaredb/src/main.rs, crates/glaredb_execution/src/engine/mod.rs, crates/glaredb_execution/src/engine/single_user.rs, crates/glaredb_execution/src/extension/mod.rs, crates/glaredb_execution/src/shell/shell.rs, crates/glaredb_wasm/Cargo.toml, crates/glaredb_wasm/src/session.rs, crates/glaredb_wasm/src/shell.rs
```
GlareDB Shell
Preview (0.0.98)
glaredb> select spark.expm1(a) from generate_series(0, 5) g(a);
┌────────────────────┐
│ expm1              │
│ Float64            │
├────────────────────┤
│                  0 │
│ 1.7182818284590453 │
│   6.38905609893065 │
│ 19.085536923187668 │
│ 53.598150033144236 │
│  147.4131591025766 │
└────────────────────┘
glaredb> select spark.csc(a) from generate_series(0, 5) g(a);
│ csc                 │
│ Float64             │
├─────────────────────┤
│                 inf │
│  1.1883951057781212 │
│  1.0997501702946164 │
│   7.086167395737187 │
│ -1.3213487088109022 │
│ -1.0428352127714058 │
```
```
glaredb> select * from list_functions() where schema_name = 'spark'; …
```
=> feat: Extension example (spark functions)

crates/glaredb_execution/src/explain/formatter.rs
```
glaredb> EXPLAIN SELECT 5 = ANY(SELECT * FROM ints);
┌───────────┬──────────────────────────────────────────────────────────────────────────────────────────────┐
│ plan_type │ plan                                                                                         │
│ Utf8      │ Utf8                                                                                         │
├───────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ unoptimi… │ Project                                                                                    + │
│           │   ├ location: Any                                                                          + │
│           │   └ projections: [__generated_visited_bool] …
```
=> chore: Trim trailing newline in explain strings

crates/glaredb_core/src/arrays/row/row_layout.rs, crates/glaredb_core/src/functions/documentation.rs, crates/glaredb_core/src/functions/table/builtin/list_entries.rs
```
glaredb> select distinct function_name, category from list_functions();
┌───────────────┬──────────┐
│ function_name │ category │
│ Utf8          │ Utf8     │
├───────────────┼──────────┤
│ csc           │ numeric  │
│ expm1         │ numeric  │
│ supplier      │ table    │
│ orders        │ table    │
│ lineitem      │ table    │
│ nation        │ table    │
│ nation        │ NULL     │
│ region        │ table    │
│ region        │ NULL     │
│ part          │ table    │
│ customer      │ table    │
│ partsupp      │ table    │
│ -             │ NULL     │
│ /             │ NULL     │
│ <             │ general  │
│ <=            │ general  │
│ >             │ general  │
│ >=            │ general  │
│ asin          │ numeric  │
│ tan           │ numeric  │
│ radians       │ numeric …
```
=> feat: Add `category` column for `list_functions`

crates/glaredb_core/src/shell/mod.rs
=> chore: Remove 'preview' from shell message

crates/glaredb_core/src/testutil/array_assert.rs, crates/glaredb_core/src/testutil/mod.rs
Example
```
thread 'testutil::array_assert::tests::assert_i32_arrays_eq_simple' panicked at crates/glaredb_core/src/testutil/array_assert.rs:155:9:
Arrays not equal! Difference found at row index 2
┌────────┬────────┐
│ array0 │ array1 │
│ Int32  │ Int32  │
├────────┼────────┤
│      4 │      4 │
│      5 │      5 │
│      6 │      7 │
└────────┴────────┘
```
=> chore: Use IS NOT DISTINCT FROM to assert array equality in tests

crates/glaredb_core/src/expr/mod.rs, crates/glaredb_core/src/functions/function_set.rs, slt/standard/functions/aggregate/string_agg.slt, slt/standard/functions/chaining.slt, slt/standard/functions/scalars/boolean.slt, slt/standard/functions/scalars/string/string_concat.slt
```
glaredb> select repeat(1,2,3);
No function matches 'repeat(Int32, Int32, Int32)'. You may need to add explicit type casts.
Candidate functions:
repeat(Utf8, Int64) -> Utf8
glaredb> select add(4,5,6);
No function matches '+(Int32, Int32, Int32)'. You may need to add explicit type casts.
Candidate functions:
+(Float16, Float16) -> Float16
+(Float32, Float32) -> Float32
+(Float64, Float64) -> Float64
+(Int8, Int8) -> Int8
+(Int16, Int16) -> Int16
+(Int32, Int32) -> Int32
+(Int64, Int64) -> Int64
+(Int128, Int128) -> Int128
...
23 not shown. View the full list of functions in the catalog.
```
=> feat: Better error for incorrect args to function

crates/glaredb_core/src/execution/operators/hash_aggregate/distinct_aggregates.rs, crates/glaredb_core/src/execution/operators/hash_aggregate/grouping_set_hash_table.rs, crates/glaredb_core/src/execution/operators/hash_aggregate/mod.rs, crates/glaredb_core/src/execution/operators/ungrouped_aggregate.rs
Each partitions is responsible for building a subset of the global hash tables. Reduces time spent in a locked state when building the final tables.
=> perf: Per-partition aggregate table merges

Cargo.toml, crates/docgen/Cargo.toml, crates/ext_csv/Cargo.toml, crates/ext_delta/Cargo.toml, crates/ext_iceberg/Cargo.toml, crates/ext_parquet/Cargo.toml, crates/ext_parquet/src/schema/convert.rs, crates/ext_spark/Cargo.toml, crates/ext_tpch_gen/Cargo.toml, crates/glaredb/Cargo.toml, crates/glaredb_bench/Cargo.toml, crates/glaredb_core/Cargo.toml, crates/glaredb_core/src/runtime/filesystem/directory.rs, crates/glaredb_error/Cargo.toml, crates/glaredb_http/Cargo.toml, crates/glaredb_http/src/gcs/directory.rs, crates/glaredb_http/src/gcs/filesystem.rs, crates/glaredb_http/src/gcs/list.rs, crates/glaredb_http/src/s3/directory.rs, crates/glaredb_http/src/s3/filesystem.rs, crates/glaredb_http/src/s3/list.rs, crates/glaredb_parser/Cargo.toml, crates/glaredb_proto/Cargo.toml, crates/glaredb_python/Cargo.toml, crates/glaredb_rt_native/Cargo.toml, crates/glaredb_slt/Cargo.toml, crates/glaredb_wasm/Cargo.toml, crates/logutil/Cargo.toml, slt/gcs/public/glob.slt, slt/s3/public/glob.slt
```
glaredb> SELECT * FROM glob('s3://glaredb-public/testdata/csv/glob_numbers/**/{3,5}00.csv') ORDER BY 1;
┌────────────────────────────────────────────────────────────────────┐
│ filename                                                           │
│ Utf8                                                               │
├────────────────────────────────────────────────────────────────────┤
│ s3://glaredb-public/testdata/csv/glob_numbers/deep/nested1/300.csv │
│ s3://glaredb-public/testdata/csv/glob_numbers/deep/nested1/500.csv │
│ s3://glaredb-public/testdata/csv/glob_numbers/deep/nested2/300.csv │
│ s3://glaredb-public/testdata/csv/glob_numbers/deep/nested2/500.csv │
│ s3://glaredb-public/testdata/csv/glob_numbers/nested1/300.csv      │
│ …
```
=> fix: Handle parsing object store paths manually when determining glob segments

crates/glaredb_core/src/execution/operators/hash_join/hash_table/mod.rs, slt/standard/join/inner_join_eq_neq.slt
Previously assumed that join keys were provided with equalities coming in first, but that's not actually guaranteed.
=> fix: Handle out of order relative join keys correctly

crates/glaredb_core/src/logical/logical_join.rs, crates/glaredb_core/src/optimizer/join_reorder/graph.rs, slt/standard/join/in_semi_join_with_filter.slt, slt/tpchbench/q18.slt
We currently support only "left" semi joins and thus can't freely flip them. During join reordering, we correctly reordered the child nodes after rebuilding the graph to to ensure that they're on the right side, but omitted reordering the associated filters that were pushed down, causing a planning error.
=> fix: Ensure filters pushed through semi joins during reorder are on correct side

crates/ext_parquet/src/column/column_reader.rs, crates/ext_parquet/src/column/encoding/byte_stream_split.rs, crates/ext_parquet/src/column/encoding/delta_binary_packed.rs, crates/ext_parquet/src/column/encoding/delta_byte_array.rs, crates/ext_parquet/src/column/encoding/delta_length_byte_array.rs, crates/ext_parquet/src/column/encoding/dictionary.rs, crates/ext_parquet/src/column/encoding/mod.rs, crates/ext_parquet/src/column/encoding/plain.rs, crates/ext_parquet/src/column/encoding/rle_bit_packed.rs, crates/ext_parquet/src/column/page_reader.rs, crates/ext_parquet/src/column/struct_reader.rs, crates/ext_parquet/src/functions/scan.rs, crates/ext_parquet/src/reader.rs, slt/parquet/binary_rle_dict_defs.slt
Some were erroneously viewing `levels` as _all_ levels we're reading across all pages for a single batch, and not just the levels we're reading for a single page.
=> fix: Properly handle definition levels in some parquet decoders

.github/workflows/bench.yaml, .gitignore, Cargo.lock, bench_bin/Cargo.toml, bench_bin/bench_runner.rs, crates/glaredb_bench/Cargo.toml, crates/glaredb_bench/src/benchmark.rs, crates/glaredb_bench/src/lib.rs, crates/glaredb_bench/src/runner.rs, test_bin/Cargo.toml
```
% cargo bench --bench bench_runner -- bench/micro/
...
running 16 tests
test bench/micro/min_max_generate_series_10M.bench                ... bench:  20,312,014 ns/iter (+/- 0)
test bench/micro/limit/limit_early_stop.bench                     ... bench:      67,111 ns/iter (+/- 0)
test bench/micro/aggregates/redundant_group_by_exprs_64.bench     ... bench: 819,351,208 ns/iter (+/- 0)
test bench/micro/aggregates/many_small_string_groups_1M.bench     ... bench: 219,555,069 ns/iter (+/- 0)
test bench/micro/aggregates/many_int_groups_1M.bench              ... bench: 129,761,610 ns/iter (+/- 0)
test bench/micro/aggregates/many_distinct_values.bench            ... bench: 147,719,597 ns/iter (+/- 0)
test bench/micro/aggregates/corr_10M_points.bench                 ... bench: 643,271,083 …
```
=> chore: Use libtest mimic for bench runner

crates/glaredb_core/src/arrays/format/pretty/table.rs
Closes https://github.com/GlareDB/glaredb/issues/3846
```
glaredb> SELECT event_type, count(*) FROM ecommerce GROUP BY event_type;
┌────────────┬───────────┐
│ event_type │ count     │
│ Utf8       │ Int64     │
├────────────┼───────────┤
│ cart       │  19114063 │
│ view       │ 385746849 │
│ purchase   │   6848824 │
└────────────┴───────────┘
```
=> fix: Sample columns across batches when computing table widths

crates/glaredb_core/src/arrays/array/float.rs, crates/glaredb_core/src/arrays/array/mod.rs, crates/glaredb_core/src/functions/cast/builtin/to_primitive.rs
Fixes Miri issue. `powi` doesn't guarantee precision.
=> fix: Replace powi with powers table during float->decimal cast
